### ISSUE TITLE
12.6.2.3 Require a new array for each call with a parameter array and no arguments?

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#101]
In 13.6.2.3 we have:

> In this case, the invocation creates an instance of the parameter array type with a length corresponding to the number of arguments, [...]

and then in an example:

> In particular, note that an empty array is created when there are zero arguments given for the parameter array.

This means a compiler can't optimize to reuse a single empty array with the right element type for all calls to a method with a parameter array, when no arguments are passed. We could potentially soften the language here.

Note that C# 6 was potentially going to revisit parameter arrays for `IEnumerable<T>` parameters, but the feature was at least temporarily dropped - if this whole area is going to be revisited later, we might want to defer any changes.

**Comment by KalleOlaviNiemitalo** [comment]
The C# 6 standard does not require a new empty array for `params`: <https://github.com/dotnet/csharpstandard/blob/721ef2964efeb5b4b803e856a00094dc4fe21bb7/standard/expressions.md?plain=1#L648>

That text came from <https://github.com/dotnet/csharpstandard/pull/377>, which said "Fixes https://github.com/dotnet/csharpstandard/issues/200".  Consider this a duplicate of https://github.com/dotnet/csharpstandard/issues/200 then?

**Comment by Nigel-Ecma** [comment]
@KalleOlaviNiemitalo – yes, this is an orphan clone, or something like that!

Closing, thanks

**Comment by KalleOlaviNiemitalo** [comment]
> Closing, thanks

You didn't actually close this yet

**Comment by Nigel-Ecma** [comment]
Well I did, GitHub just likes being contrary, at least with me 😉. I’ll try to sate it’s ego and if that fails @jskeet or @BillWagner will have to step in as our accomplished GitHub whisperers.
