### ISSUE TITLE
Make AsyncMethodBuilderAttribute a "Reserved attribute"

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#1031]
In V7, in [§15.15.1](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/classes.md#15151-general), we introduced the new attribute type `AsyncMethodBuilderAttribute` and in the library annex [§C.3](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/standard-library.md#c3-standard-library-types-not-defined-in-isoiec-23271), we showed its declaration.

It seems to me that this attribute needs to be recognized by the compiler, so it needs to have its own section in [§22.5, Reserved attributes](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/attributes.md#225-reserved-attributes). If members agree, I'll write up the PR to add that (small/simple) section.

**Comment by jskeet** [comment]
We agree, the attribute should be there. @RexJaeschke will create a PR.

**Comment by RexJaeschke** [comment]
Closed by https://github.com/dotnet/csharpstandard/pull/1035.
