### ISSUE TITLE
Shall the Chapter `Lexical structure` Introduce Keyword Operators Properly?

### ISSUE THREAD

**Issue by TimothyLiuAtGoogle** [dotnet/csharpstandard#1032]
**Describe the bug**
* In the section `6.4.4 Keywords`, some keywords are also operators. For example, `new` and `as`. The spec doesn't mention it.
* In the section `6.4.6 Operators and punctuators`, only those non-keyword operators are listed.
* In the section `12.8.16 The new operator`, the spec formally says `new` is an operator.

Somehow it might be a logic loophole.

**Comment by RexJaeschke** [comment]
@[TimothyLiuAtGoogle](https://github.com/TimothyLiuAtGoogle). 

Thanks for your input.

My initial reaction is, “No further explanation is necessary!”

Yes, `new` (as well as `sizeof`, and `typeof`) is an operator that is spelled as a keyword, but, first, let’s look at specs for several other (very popular) languages to see how they handle this:

- Java: `new` is an expansion of the grammar rule *Keyword*. Like the C# spec, the grammar rule *Operator* does not include `new`. And like the C# spec, there is no mention in either the “Keywords” or “Operators” sections about operators spelled as keywords.
- C++: `new` is an expansion of the grammar rule *keyword*. Like the C# spec, the grammar rule *operator-or-punctuator* does not include `new`. Like the C# spec, there is no mention in either the “Keywords” or “Operators and punctuators” sections about operators spelled as keywords. That said, C++ has the oddity of alternate spellings for some operators; e.g., `and` being equivalent to `&&` and `bitand` being equivalent to `&`. While the identifier versions are mentioned in the Keywords section, they are *not* expansions of the *keyword* grammar rule.
 
So, I think the C# spec is in good company by not saying more!

Keep in mind that the purpose of Chapter 6 is to describe the lexical grammar; that is, how to form source tokens. Chapter 12 then covers the syntactic grammar and semantics of operators.

To be sure, there are complexities; for example, some operators consist of multiple tokens (`>>`, `>>=`, `()`, and `[]`), yet only the first two of these are called out in the C# spec’s “Operators and punctuators” section.

What is the problem you are looking to solve? Is there confusion/ambiguity here?

**Comment by TimothyLiuAtGoogle** [comment]
@RexJaeschke 

Thank you so much for the quick response!

When teaching students and writing books, I often refer to the C# spec. The problem is I have to explain to the students that `new` is an operator and we will use it to form expressions, but it's not listed in `6.4.6 Operators and punctuators`. As same as what you mentioned, I also tell the students - event ISO:14882 (C++ Spec) does the similar thing.

**Comment by RexJaeschke** [comment]
@[TimothyLiuAtGoogle](https://github.com/TimothyLiuAtGoogle).

The important thing for readers of the spec to understand is that 6.4.6, "Operators and punctuators" is *not* about operators, per se, but rather, it's a list of source tokens that are classified as operator tokens, separate from 6.4.4, "Keywords," which is a list of source tokens that are classified as keyword tokens.

Closing this issue, without action.
