### ISSUE TITLE
Typo in 23.5.2 Pointer arrays - "usafe" instead of "unsafe"

### ISSUE THREAD

**Issue by vritme** [dotnet/csharpstandard#1037]
### Type of issue

Typo

### Description

Typo in section [23.5.2 Pointer arrays](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/unsafe-code.md#2352-pointer-arrays), line 348 - "usafe" instead of "unsafe".
> Arrays of pointers can be constructed using *array_creation_expression* (§12.8.16.5) in an **usafe** context.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/unsafe-code

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/unsafe-code.md

**Comment by jskeet** [comment]
Fixed in #1038.
