### ISSUE TITLE
Add dependabot for automatic package updates

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#1048]
Now that all our packages are up to date in our tools, with all the tests passing, we could save ourselves some ongoing work by using [Dependabot](https://docs.github.com/en/code-security/dependabot).

I recommend a configuration similar to that used in [`dotnet/docs`]:  An action runs as a cron job that opens a single PR per solution when one of the dependencies has an updated, released, package. 

Our CI job would ensure the tools build with the updated package, and our tests (minimal though they are), all pass.

**Comment by BillWagner** [comment]
@jskeet 

I can do this, if you agree that it's a good idea.

**Comment by jskeet** [comment]
Yup, that works for me.
