### ISSUE TITLE
Examples for character literals.

### ISSUE THREAD

**Issue by logeshkumars0604** [dotnet/csharpstandard#1064]
### Type of issue

Typo

### Description

The below example in [6.4.5.5 Character literals](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#6455-character-literals)

> string good = "x9Good text";
> string bad = "x9Bad text";

shouldn't be like the below.

> string good = "\x9Good text";
> string bad = "\x9Bad text";

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#838-the-decimal-type

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/types.md

**Comment by jskeet** [comment]
Content source is actually https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/lexical-structure.md

Will send a PR.
