### ISSUE TITLE
[Epic] Specify nullable reference types in C# 8

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#1085]
#700 is a draft which will be useful, but we're going to try to do this in multiple small PRs.

The current planned task list is:

- [x] #1088
- [x] #1089 
- [x] #1090 
- [x] #1091
- [x] #1092
- [x] #1093
- [x] #1094

**Comment by KalleOlaviNiemitalo** [comment]
Are [MaybeNullWhenAttribute](https://learn.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.maybenullwhenattribute?view=netstandard-2.1) and others going to be standardised?

**Comment by BillWagner** [comment]
> Are [MaybeNullWhenAttribute](https://learn.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.maybenullwhenattribute?view=netstandard-2.1) and others going to be standardised?

Yes, see #1092

**Comment by KalleOlaviNiemitalo** [comment]
Does any of those issues cover how variance of generic parameters should affect warnings about identity conversions:

```csharp
using System;
public class C {
    // f1 is a delegate that takes string? and returns string.
    public void M(Func<string?, string> f1) {
        // Nullability of type arguments does not match,
        // but there is no warning, because of variance.
        Func<string, string?> f2 = f1;

        // Convert back to the original type.
        // This causes a warning.
        Func<string?, string> f3 = f2;
    }
}
```


<https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/nullable-reference-types-specification.md> doesn't seem to mention this.

I'm not sure whether this behaviour is C# 8 or 9, but I guess 8.

**Comment by BillWagner** [comment]
Terminology question: Do we want to use "nullable context" or "null analysis context"?  Alternative is "set the flags in the nullable context".

See https://github.com/dotnet/csharpstandard/pull/1123/files#r1672741166

However, note that the null state analysis is *always* being done. The comment states that the context may impact that.
