### ISSUE TITLE
[Nullable Reference Types] Specify behavior for nullable analysis attributes

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#1092]
There are a number of attributes read by the compiler that support nullable flow analysis, and provide some additional syntactic rules where those attributes are applied.

The list of attributes, and how that affects the syntax where applied should be normative. How those attributes affect flow analysis may include both normative and informative text.

**Comment by BillWagner** [comment]
Adding the meeting discuss label based on discussion in our September meeting.

Do any of these attributes need to be added to the standard?

They are used only to inform the static null state analysis for the compiler.

**Comment by jskeet** [comment]
Decision on 2024-10-02:

- we'll *list* the attributes normatively, saying they are reserved for nullable analysis
- as per other decisions, we will not go into detail and require *specific* nullable analysis
- we will provide one or two informative examples in detail about what "a compiler" *could* do
