### ISSUE TITLE
boolean_expression     : expression     ;

### ISSUE THREAD

**Issue by hossain666** [dotnet/csharpstandard#1099]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1224-boolean-expressions

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md

**Comment by jskeet** [comment]
It's not at all clear to me that there's an issue here. Please clarify *exactly* what you believe to be wrong.

**Comment by jskeet** [comment]
Closing as spam.
