### ISSUE TITLE
14 Namespaces section doesn't describe file scoped namespace declarations

### ISSUE THREAD

**Issue by knutwannheden** [dotnet/csharpstandard#1113]
(I was unsure if I should report this using the feedback button or not and decided to report a "bug" instead. I hope that was the right thing to do.)

Reading through https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces I don't see any mention of file scoped namespace declarations [as introduced in C# 10](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration). Also the ANTLR grammar in Annex A doesn't properly account for file spaced namespace declarations. Only the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace page describes how file scoped namespace declarations work.

**Comment by jskeet** [comment]
That's because we haven't reached C# 10 yet. We're working on standardizing C# 8, then we'll move on to 9, then 10.

(We *hope* to catch up to "current" eventually, but it's a long road.)

**Comment by knutwannheden** [comment]
Thanks for clarifying. Feel free to close the issue again. I was just unsure due to the inconsistency in the docs.
