### ISSUE TITLE
Parameters #2: Alternate Terms for a Parameter Kind

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#1159]
Recently, I had cause to review the spec in terms of function parameters, and argument passing. [This was regarding adding future support for `ref readonly` parameters.] I found a lot of places where the text could be considerably simplified, made consistent, or have duplication of normative text removed. This issue deals with one aspect, and is *not* intended to result in any semantic changes. Rather, it is intended to create a better base on which to add future feature specs. Hopefully, we can decide offline on each proposal without taking up TG2 meeting time.

## Issue

Variables.md, [9.2.8 Input parameters](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/variables.md#928-input-parameters), states

>A parameter declared with an `in` modifier is an ***input parameter***.

So, the term “input parameter” is defined (and matches the parent section name). However, while 61 occurrences of text about input parameters uses that term, 33 occurrences use “`in` parameter” instead, for no obvious reason and with no value added.

The same situation exists for “output/`out` parameter” ([9.2.7 Output parameters](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/variables.md#927-output-parameters)) and “reference/`ref` parameter” ([9.2.6 Reference parameters](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/variables.md#926-reference-parameters)).

[There is no such duplication for “value parameter.” [9.2.5 Value parameters](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/variables.md#925-value-parameters) states: “A parameter declared without an `in`, `out`, or `ref` modifier is a ***value parameter***, and “value parameter” is used throughout.]

## Proposal

- Change all “`in` parameter” to “input parameter.”
- Change all “`out` parameter” to “output parameter.” 
- Change all “`ref` parameter” to “reference parameter.”
- Also, change such text not having the backticks, as in “out parameter.”
- Change the term definition “***by-reference*** parameter” to “***by-reference parameter***.”
- Change all enumerated lists “input, output, and/or reference parameter” to the corresponding group term “by-reference parameter.”

## Discussion

The term “by-reference parameters” is defined in [15.6.2.3.1 General](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/classes.md#156231-general) and only referenced in Clause 15. It’s simply used to organize related subclauses as a group, so let’s use it instead of an enumerated list of its members.

**Comment by RexJaeschke** [comment]
@jskeet If you can add a thumbs-up to Nigel's, I'll make the changes.

**Comment by jskeet** [comment]
Yes, this definitely seems sensible to me.

**Comment by RexJaeschke** [comment]
On the 2024-09-04 TG2 call we agreed with Rex's proposal. Rex will create a PR for this.
