### ISSUE TITLE
§15.4 states that constant members can be reference types.

### ISSUE THREAD

**Issue by praeceptum** [dotnet/csharpstandard#1165]
The standard states that constant members can be reference types:

[15.4 Constants](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/classes.md#154-constants)

> The _type_ specified in a constant declaration shall be `sbyte`, `byte`, `short`, `ushort`, `int`, `uint`, `long`, `ulong`, `char`, `float`, `double`, `decimal`, `bool`, `string`, an _enum_type_, or a _reference_type_.

However, this is only true for the reference type `string` in particular, which is enumerated separately, and not reference types in general.

**Comment by KalleOlaviNiemitalo** [comment]
This is a constant with a non-`string` reference type:

```csharp
public class C {
    const C dummy = null;
}
```

**Comment by KalleOlaviNiemitalo** [comment]
And there's a note about that already:

> *Note*: As described in §12.23, a *constant_expression* is an expression that can be fully evaluated at compile-time. Since the only way to create a non-null value of a *reference_type* other than `string` is to apply the `new` operator, and since the `new` operator is not permitted in a *constant_expression*, the only possible value for constants of *reference_type*s other than `string` is `null`. *end note*

<https://github.com/dotnet/csharpstandard/blob/dd40c16c9bc6bc51b336f3bcfbd75db05bac798e/standard/classes.md?plain=1#L1483>

**Comment by praeceptum** [comment]
@KalleOlaviNiemitalo You are correct.  I didn't see the note 'down there'.

Closing issue.
