### ISSUE TITLE
Minor tweaks to the handling of right-associative operators

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#1166]
@Nigel-Ecma If you agree with this, I'll turn it into a PR for your approval.

According to the ANTLR book, p. 72:

> By default, ANTLR associates operators left to right as we’d expect for `*` and `+`. Some operators like exponentiation group right to left, though, so we have to manually specify the associativity on the operator token using option `assoc`.

In [§12.4.2](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#1242-operator-precedence-and-associativity) we have the following:

> When an operand occurs between two operators with the same precedence, the ***associativity*** of the operators controls the order in which the operations are performed:
>
> - Except for the assignment operators and the null coalescing operator, all binary operators are ***left-associative***, meaning that operations are performed from left to right.
>     > *Example*: `x + y + z` is evaluated as `(x + y) + z`. *end example*
> - The assignment operators, the null coalescing operator and the conditional operator (`?:`) are ***right-associative***, meaning that operations are performed from right to left.
>     > *Example*: `x = y = z` is evaluated as `x = (y = z)`. *end example*

I propose two tweaks to this text:

- Include the `=>` operator, as [§12.19.1](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#12191-general) states that it too is right-associative.
- Add a Note stating that the ANTLR grammar as presented in this spec does *not* include uses of the option `assoc` for right-associative operators.

As a result, the proposed rewrite of the §12.4.2 text above is, as follows:

> When an operand occurs ...
>
> - Except for the assignment operators, the null coalescing operator, and `=>`, all binary operators are ***left-associative***, ....
>     > *Example*: `x + y + z` is evaluated as `(x + y) + z`. *end example*
> - The assignment operators, the null coalescing operator, the conditional operator (`?:`), and `=>`, are ***right-associative***, ....
>     > *Example*: `x = y = z` is evaluated as `x = (y = z)`. *end example*
>    
>
>    
>     > *Note*: By default, ANTLR associates operators left to right. As such, operators associating right to left need to be marked with the option `<assoc=right>`. The ANTLR grammar presented for these operators in this spec is *not* so marked. *end note*

**Comment by KalleOlaviNiemitalo** [comment]
This reminds me about the following, which shows how the left-associativity of the addition operator can prevent a compile-time optimization: [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBkCWAdgI7YCiAHgA4BOApgM4P4D2hDA3MsrOgMLoA3snSjMAVgA8WVABpMcVAD50AcToAXACJ0ANnQDmAQw10AFAEohIsbagB2dA3QBeFQCIj79GHTuARt6+zr7uAMZBfsDuXEi2AL42opS0jMxs0lIy8jJKKuoaKfRMrISW1nG2Yg5Orh5ePn6BjSF+EY3u0bEJyIlIQA===)

```csharp
using System;
using System.Linq.Expressions;

class C {
    Func<string, string> GetDelegate() {
        return s => "a" + "b" + s + "c" + "d";
    }
    Expression<Func<string, string>> GetExpression() {
        return s => "a" + "b" + s + "c" + "d";
    }
}
```

In GetDelegate, Roslyn optimizes the expression to `string.Concat("ab", s, "cd")`.

In GetExpression however, it makes an expression tree for `(("ab" + s) + "c") + "d"`; it does not concatenate "c" and "d" at compile time.

§8.6 (Expression tree types) allows this behavior; no change is needed in the standard.

**Comment by KalleOlaviNiemitalo** [comment]
> * _Note_: By default, ANTLR associates operators left to right. As such, operators associating right to left need to be marked with the option `<assoc=right>`. The ANTLR grammar presented for these operators in this spec is _not_ so marked. _end note_

I'd prefer it if the note explained _why_ the operators are not so marked: because the grammar rules for right-associative operators define the operands such that a left-associative parse is not possible.  For example,

```antlr
assignment
    : unary_expression assignment_operator expression
    ;
```

where the left operand is a *unary_expression* rather than *expression*.

**Comment by RexJaeschke** [comment]
I didn't propose adding the notation to the grammar, as I thought that would be an unnecessary distraction. And I didn't think further explanation in the note was needed, based on the statement we make in [§6.2.2](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/lexical-structure.md#622-grammar-notation):

> The lexical and syntactic grammars are presented in the ANTLR grammar tool’s Extended Backus-Naur form.
>
> While the ANTLR notation is used, this specification does not present a complete ANTLR-ready “reference grammar” for C#; writing a lexer and parser, either by hand or using a tool such as ANTLR, is outside the scope of a language specification. With that qualification, this specification attempts to minimize the gap between the specified grammar and that required to build a lexer and parser in ANTLR.

**Comment by Nigel-Ecma** [comment]
It is quite usual for grammar rules to be constructed so as to enforce the associatively required by a language, and C#’s grammar uses this approach. The ANTLR `assoc` is for grammars which do not do this.

So there is no need to and any notes to the Standard.

**Comment by Nigel-Ecma** [comment]
> This reminds me about the following, which shows how the left-associativity of the addition operator can prevent a compile-time optimization:

@KalleOlaviNiemitalo – I’d argue this stems from the overloading of numerical addition (which is associative) and string concatenation (which isn’t), so it’s a convenience trade-off.

That said I think a compiler can apply any optimisation that it can show doesn’t affect the result/behaviour of the program inappropriately/incorrectly. However I except this is a small enough corner case that the compiler writers decided to skip the optimisation.

**Comment by KalleOlaviNiemitalo** [comment]
> numerical addition (which is associative)

For integers, it's not associative in `checked` context.

> string concatenation (which isn’t)

Huh?  Do you have an example of `(a + b) + c != a + (b + c)` with strings?

**Comment by jskeet** [comment]
> Huh? Do you have an example of (a + b) + c != a + (b + c) with strings?

Well, with a mixture of strings and integers:

`("x" + 2) + 5 != "x" + (2 + 5)` for example. Not sure whether that's what Nigel was referring to.

**Comment by Nigel-Ecma** [comment]
@KalleOlaviNiemitalo  & @jskeet – Apologies, it is a typo, I should have typed "numerical addition (which is left-associative)". So `+` represents both a **left**-associative (addition) and an associative (concatenation) operators, while the grammar parses it as left-associative.

**Comment by RexJaeschke** [comment]
@Nigel, based upon your [comment](https://github.com/dotnet/csharpstandard/issues/1166#issuecomment-2329813994), I'm happy to close this issue without action. OK?

**Comment by Nigel-Ecma** [comment]
@RexJaeschke – Yes, and I'll press the "Close with comment" to save a step
