### ISSUE TITLE
Typ0

### ISSUE THREAD

**Issue by Playgirlkaybraz11** [dotnet/csharpstandard#1169]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#73-declarations

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md

**Comment by Playgirlkaybraz11** [comment]
#974 #1120 #1166 #1135 #

**Comment by BillWagner** [comment]
closing as spam.
