### ISSUE TITLE
Post/pre inc/dec "typically"?

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#1196]
[§12.8.16](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#12816-postfix-increment-and-decrement-operators) & [§12.9.6](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#1296-prefix-increment-and-decrement-operators):

> Typically, the result of `x++` or `x--` is the value of `X` *before* the operation, whereas the result of `++x` or `--x` is the value of `X` *after* the operation.

Bug: *Typically*? The definitions in both clauses clearly define it as *always*.

Typo: 2 × `X` rather than `x`.

**Comment by RexJaeschke** [comment]
@Nigel-Ecma FYI, I corrected the first section ref # and made both links. I agree with removing "typically" in both places, and to the x-to-X edits. Once we get 1 or 2 thumbs-ups, I can write up a PR if you like.

**Comment by Nigel-Ecma** [comment]
@RexJaeschke - I doubt this will be controversial, happy for you to go ahead. I discovered it while in the midst of something else so dropped it as a note to come back to.On 5 Nov 2024, at 4:59 AM, Rex Jaeschke ***@***.***> wrote:﻿
@Nigel-Ecma FYI, I corrected the first section ref # and made both links. I agree with removing "typically" in both places, and to the x-to-X edits. Once we get 1 or 2 thumbs-ups, I can write up a PR if you like.

**Comment by RexJaeschke** [comment]
@Nigel-Ecma I was just about to create a PR for this when I spotted some other (related) things to fix.

I think the following 3 occurrences of uppercase `X` (delimited by me with [[...]]) should also be changed to lowercase `x`, as no uppercase `X` is declared in these sections:

[§12.8.16](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#12816-postfix-increment-and-decrement-operators):

- If `x` is classified as a variable:
  - ...
  - The value returned by the operator is converted to the type of `[[X]]` and stored in the location given by the earlier evaluation of `x`.

[§12.9.6](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#1296-prefix-increment-and-decrement-operators):

- If `x` is classified as a property or indexer access:
  - ...
  - The get accessor of `[[X]]` is invoked.
  - ...
  - The value returned by the operator is converted to the type of `x`. The set accessor of `[[X]]` is invoked with this value as its value argument.
  - ...

Assuming you agree, I'll create the PR.

**Comment by Nigel-Ecma** [comment]
@RexJaeschke – Well spotted, I agree.
