### ISSUE TITLE
18.4.2 No mention of out/ref parameters and output safety

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#134]
Interface indexers in 19.4.5 have this paragraph:

> All the formal parameter types of an interface indexer shall be input-safe . In addition, any out or ref formal parameter types shall also be output-safe. Note that even out parameters are required to be input-safe, due to a limitiation of the underlying execution platform.

19.4.2 only has:

> Each formal parameter type of an interface method shall be input-safe (§19.2.4.2), and the return type shall be either void or output-safe.

The same restrictions should apply for both indexers and methods, I believe. They should probably use the same wording too (for parameters; the return type for indexers is specified separately), in terms of all/each and whether or not there's a back reference to 19.2.4.2. See ECMA-TC49-TG2/spec#645 for an issue around "underlying platform" in 19.4.5 and ECMA-TC49-TG2/spec#644 for the space typo.

Proposal: both should have

> Each formal parameter type of an interface method shall be input-safe (§19.2.4.2). In addition, any `out` or `ref` formal parameter types shall also be output-safe.

... and either both have whatever note is determined in ECMA-TC49-TG2/spec#645, or just 19.4.2. (It would be odd to only have a note on the second occurrence.)

The same wording should be used for 21.2 as well (delegates).

**Comment by Nigel-Ecma** [comment]
This looks to be complete (PR's approved & merged) so I'll close it. If I'm wrong please reopen!
