### ISSUE TITLE
V6 Feature: Improved overload resolution

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#157]
What's new in C#6 at https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#improved-overload-resolution, says:

> This last feature is one you probably won't notice. There were constructs where the previous version of the C# compiler may have found some method calls involving lambda expressions ambiguous.

Does this involve something previously disallowed or unspecified, but now allowed? What, if anything, do we need to say in the spec re this?

**Comment by gafter** [comment]
Yes, I will take ownership. As a practical matter I will work on it during the month of ~~August~~ ~~September 2020~~ May 2021.

**Comment by BillWagner** [comment]
See also #283
