### ISSUE TITLE
12.7.7.2 and 12.18.2 Array access evaluation order for assignments

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#169]
13.7.7.2 (array access) suggests that evaluating an array access expression performs nullity and index checks.

13.18.2 (simple assignment) states for an assignment `x = y`:

> - If x is classified as a variable:
>   - x is evaluated to produce the variable.
>   - y is evaluated and, if required, converted to the type of x through an implicit conversion (§12.2).

That all sounds fine, but my understanding of reality is that the nullity check and array index check are only performed *after* `y` is evaluated. Sample code to show that...

**Null check comes after RHS**

```csharp
using System;

public class Test
{
    static void Main()
    {
        int[] array = null;
        array[10] = SideEffect(); // Prints "Side effect" then throws
    }

    private static int SideEffect()
    {
        Console.WriteLine("Side effect");
        return 10;
    }
}
```

**Index check comes after RHS**

```csharp
using System;

public class Test
{
    static void Main()
    {
        int[] array = new int[5];
        array[10] = SideEffect(); // Prints "Side effect" then throws
    }

    private static int SideEffect()
    {
        Console.WriteLine("Side effect");
        return 10;
    }
}
```

I have very vague recollections of this being properly specified somewhere, but I can't easily find it - and assuming it *does* exist, I think we should have a reference to it within at least one of these sections.

Assigning to Mads initially as he may well know what's going on...

**Comment by jskeet** [comment]
Assigned to @MadsTorgersen to consider before the next meeting.

**Comment by MadsTorgersen** [comment]
Jon is right.

According to [12.7.7.1 Element access](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12771-general) `a[i]` is an array access when `a` is of an array type.

In [12.7.7.2 Array access](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12772-array-access) such an array access is classified as a variable, and it is described in detail how to compute the location referenced by the variable.

In [12.18.2 Simple assignment](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12182-simple-assignment) it is clear that the variable on the left-hand side (the array access) is computed before the right-hand side:

> - If `x` is classified as a variable:
>   - `x` is evaluated to produce the variable.
>   - `y` is evaluated and, if required, converted to the type of `x` through an implicit conversion ([§11.2](conversions.md#112-implicit-conversions)).
>   - If the variable given by `x` is an array element of a *reference_type*, a run-time check is performed to ensure that the value computed for `y` is compatible with the array instance of which `x` is an element. The check succeeds if `y` is `null`, or if an implicit reference conversion ([§11.2.7](conversions.md#1127-implicit-reference-conversions)) exists from the type of the instance referenced by `y` to the actual element type of the array instance containing `x`. Otherwise, a `System.ArrayTypeMismatchException` is thrown.
>   - The value resulting from the evaluation and conversion of `y` is stored into the location given by the evaluation of `x`.
> ...

I think that the spec'ed semantics are the most elegant and orthogonal, and that the compiler behavior is essentially a bug. Of course it is out of the question to change the compiler behavior after 20 years of people depending on it. So our choices seem to be:

1. Do nothing. We leave this as a discrepancy caused by a compiler bug.
2. Change the spec to match compiler semantics. 

If we want to pursue the latter, I think that we still want to classify an array access as a variable, so that it can continue to work the same elsewhere (including being `ref`'ed etc.). We would instead special-case assignment (probably both [12.18.2 Simple assignment](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12182-simple-assignment) and [12.18.3 Compound assignment](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12183-compound-assignment)) to handle arrays before other variables.

My inclination is to do nothing and live with the discrepancy. If we decide to go with the latter, I can try to draft the specific additions to those two sections.

**Comment by jskeet** [comment]
This isn't the first time we've come up against "Hmm - it's not right, but it's not worth changing." Places where if we were writing an annotated standard, we might have an annotation.

Perhaps we should consider something that could live within the standard, so that the information isn't lost (or separated from the standard, as it *effectively* is in a closed issue - think [Raiders of the Lost Ark closing scene](https://www.youtube.com/watch?v=i5pd1U6yXe0&t=82s)). It might make sense to remove such annotations from the Word conversion (at least optionally) so it would never be part of the *official* standard, but it would be useful to language archaeologists.

**Comment by jskeet** [comment]
Resolution: after thinking about just adding a note, we convinced ourselves we'd like to at least see what a proper fix might look like.

**Comment by MadsTorgersen** [comment]
Here is the rule in [12.18.2 Simple assignment](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12182-simple-assignment) as it is today, abbreviating out the property-or-indexer-access part at the end:

> - If `x` is classified as a variable:
>   - `x` is evaluated to produce the variable.
>   - `y` is evaluated and, if required, converted to the type of `x` through an implicit conversion ([§11.2](conversions.md#112-implicit-conversions)).
>   - If the variable given by `x` is an array element of a *reference_type*, a run-time check is performed to ensure that the value computed for `y` is compatible with the array instance of which `x` is an element. The check succeeds if `y` is `null`, or if an implicit reference conversion ([§11.2.7](conversions.md#1127-implicit-reference-conversions)) exists from the type of the instance referenced by `y` to the actual element type of the array instance containing `x`. Otherwise, a `System.ArrayTypeMismatchException` is thrown.
>   - The value resulting from the evaluation and conversion of `y` is stored into the location given by the evaluation of `x`.
> - If `x` is classified as a property or indexer access...

Here is the best I could come up with that handles array access with the same evaluation order as the compiler:

> - If `x` is classified as a variable:
>   - If `x` is an array access  ([§12.7.7.2](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12772-array-access)) of the form  `a[i1,...,in]`:
>     - `a` and `i1`,..., `in` are evaluated.
>     - `y` is evaluated and, if required, converted to the type of `x` through an implicit conversion ([§11.2](conversions.md#112-implicit-conversions)).
>     - `x` is evaluated to produce the variable, using the results of evaluating `a` and `i1`,..., `in`.
>   - If `x` is not an array access:
>     - `x` is evaluated to produce the variable.
>     - `y` is evaluated and, if required, converted to the type of `x` through an implicit conversion ([§11.2](conversions.md#112-implicit-conversions)).
>   - If the variable given by `x` is an array element of a *reference_type*, a run-time check is performed to ensure that the value computed for `y` is compatible with the array instance of which `x` is an element. The check succeeds if `y` is `null`, or if an implicit reference conversion ([§11.2.7](conversions.md#1127-implicit-reference-conversions)) exists from the type of the instance referenced by `y` to the actual element type of the array instance containing `x`. Otherwise, a `System.ArrayTypeMismatchException` is thrown.
>   - The value resulting from the evaluation and conversion of `y` is stored into the location given by the evaluation of `x`.
> - If `x` is classified as a property or indexer access...

You may ask why the "array element of a *reference_type*" bit is necessary even for a LHS that is not syntactically an array access, and the reason is that the runtime type check needs to happen even when the LHS is e.g. a ref variable that _points_ to an array element.

**Comment by jskeet** [comment]
That looks like a *much* simpler fix than I'd expected. I'd definitely be happy to include that change - it's still easy to understand while achieving correctness.

**Comment by KalleOlaviNiemitalo** [comment]
For initializing a ref parameter with a reference to an array element, draft-v6 already specifies a runtime type check in [12.6.2.3 Run-time evaluation of argument lists](https://github.com/dotnet/csharpstandard/blob/6489755c53a1eeda32b01187fd47c3f92130c2a0/standard/expressions.md#12623-run-time-evaluation-of-argument-lists). So the `Assign(ref array[0])` call throws ArrayTypeMismatchException before the Assign method starts executing. The `elt = new object()` assignment can assume that the type matches, without needing another runtime type check.

```csharp
class Program
{
    static void Main()
    {
        object[] array = new string[1];
        Assign(ref array[0]); // Run-time type check throws ArrayTypeMismatchException, as required by standard.
    }

    static void Assign(ref object elt)
    {
        elt = new object(); // Standard should not require a run-time type check.
    }
}
```

For initializing a ref local with a reference to an array element in C# 7.0, <https://github.com/dotnet/csharpstandard/pull/213> does not seem to specify a runtime type check. That should be clarified to make it work the same way as argument evaluation. AFAIK, compilers use the `ldelema` CIL opcode for that, and ECMA-335 then specifies the type check, but there is no normative reference to ECMA-335 in the C# standard.

```C#
class Program
{
    static void Main()
    {
        object[] array = new string[1];
        ref object elt = ref array[0]; // Run-time type check throws ArrayTypeMismatchException, but this is not clear from the draft.
        elt = new object(); // Standard should not require a run-time type check.
    }
}
```

**Comment by MadsTorgersen** [comment]
@KalleOlaviNiemitalo good catch! This seems to be another way in which this part of the spec is buggy. It appears the runtime check should only happen when the LHS is _syntactically_ an array access.

Here's an updated version of my proposed change that takes that into account:

> - If `x` is classified as a variable:
>   - If `x` is an array access  ([§12.7.7.2](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#12772-array-access)) of the form  `a[i1,...,in]`:
>     - `a` and `i1`,..., `in` are evaluated.
>     - `y` is evaluated and, if required, converted to the type of `x` through an implicit conversion ([§11.2](conversions.md#112-implicit-conversions)).
>     - `x` is evaluated to produce the variable, using the results of evaluating `a` and `i1`,..., `in`.
>     - If the element type of `a` is a *reference_type*, a run-time check is performed to ensure that the value computed for `y` is compatible with the array instance that is the value of `a`. The check succeeds if `y` is `null`, or if an implicit reference conversion ([§11.2.7](conversions.md#1127-implicit-reference-conversions)) exists from the type of the value of `y` to the actual element type of the array instance that is the value of `a`. Otherwise, a `System.ArrayTypeMismatchException` is thrown.
>   - If `x` is not an array access:
>     - `x` is evaluated to produce the variable.
>     - `y` is evaluated and, if required, converted to the type of `x` through an implicit conversion ([§11.2](conversions.md#112-implicit-conversions)).
>   - The value resulting from the evaluation and conversion of `y` is stored into the location given by the evaluation of `x`.
> - If `x` is classified as a property or indexer access...

The check has been moved under the array access bullet and slightly reworded to reference `a` rather than `x`.

**Comment by MadsTorgersen** [comment]
Even if we don't end up taking the bigger proposed change here, we should still consider rewording the element type check to only apply when the LHS is an actual array access.

**Comment by jskeet** [comment]
Next step: just turning this into a PR?

**Comment by jskeet** [comment]
Agreed in the meeting - @MadsTorgersen, please create a PR and we'll go from there.

**Comment by gafter** [comment]
The proposed wording does not explain the behavior in the [following example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgMwAERNAwjQN4U3t2GEtsd8CKAbQC6NAI4QaAXhowApgHcaQ4gAZhAbl592sBDSjSaxLeR0cAsgAoJcAwEpTfAL4VtdWvmIA2OgBYaayFRCDs9Bx4zcxoIQShhADoADyMLQitHd1co9ndqOh8DGH00jPdWHJ0vBK8ATisAIjSGzMq+fAB2GkInDmzsinz6fkj22nCk02ygA) in which the left-hand-side is not an array access (syntactically or semantically) and yet the right-hand-side is evaluated before the array is indexed.

```csharp
using System;
public class C {
    public static void Main() {
        Q[] qa = new Q[10];
        int i = 1;
        M(qa, i);
    }

    public static void M(Q[] a, int i) {
        a[i].x = M2();
    }
    
    public static int M2()
    {
        System.Console.WriteLine("M2");
        return 2;
    }
}

public class Q {
    public int x;
}
```

**Comment by gafter** [comment]
See also https://github.com/dotnet/csharpstandard/issues/401

**Comment by jskeet** [comment]
Adding to be discussed in the May meeting to see whether we just need to turn this into a PR.

**Comment by jskeet** [comment]
Just to validate that the array itself is evaluated before the RHS:

```csharp
class Program
{
    static int[] array = null;

    static void Main()
    {
        array[10] = AllocateArray();
    }

    static int AllocateArray()
    {
        array = new int[20];
        return 5;
    }
}
```

This still throws (thankfully).

**Comment by jskeet** [comment]
We're not going to change the spec, but we want to start a list of "known spec violations, where we wish it obeyed the spec". (That won't be in this repo though; it's MS-specific.)

**Comment by KalleOlaviNiemitalo** [comment]
Should a separate issue be filed for "If the variable given by x is an array element of a reference_type, a run-time check is performed" requiring a type check even when x is not syntactically E[Ei]?

**Comment by jskeet** [comment]
@KalleOlaviNiemitalo: I don't immediately follow, but yes, I'd suggest creating a new issue with an example.
