### ISSUE TITLE
Interpolated string literals: Reliance on library machinery

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#172]
***[The interpolated string literals feature is awaiting PR review in the conversion-to-markdown repo, and can be viewed in branch Rex-interpolated-string-literals.]***

***

***[I've taken the interpolated proposal as far as I can, and need help with the things mentioned below.]***

***

## A. The Library Support Machinery

In the proposed new subclause for expresisons.md, "Interpolated strings," we have

> An *interpolated_string_expression* is classified as a value. If it is immediately converted to `System.IFormattable` or `System.FormattableString` with an implicit interpolated string conversion ([§xxx](conversions.md#implicit-interpolated-string-conversions)), the interpolated string expression has that type. Otherwise, it has the type `string`.
>
> If the type of an interpolated string is `System.IFormattable` or `System.FormattableString`, the meaning is a call to `System.Runtime.CompilerServices.FormattableStringFactory.Create`. If the type is `string`, the meaning of the expression is a call to `string.Format`. In both cases, the argument list of the call consists of a format string literal with placeholders for each interpolation, and an argument for each expression corresponding to the place holders.

And in the proposed new subclause for conversions.md, "Implicit interpolated string conversions," we have 
 
> An implicit interpolated string conversion permits an *interpolated_string_expression* ([§xxx](expressions.md#interpolated-strings)) to be converted to `System.IFormattable` or `System.FormattableString` (which implements `System.IFormattable`). When this conversion is applied, a string value is not composed from the interpolated string. Instead an instance of `System.FormattableString` is created, as further described in [§xxx](expressions.md#interpolated-strings).

***

While the type `System.IFormattable` is covered by the current CLI standard (6e, 2012), `System.FormattableString` and `System.Runtime.CompilerServices.FormattableStringFactory.Create` are not, and none of them are mentioned in the v5 C# spec.

How much do we need to say in our spec re these types?

## B. Hole Content Processing

In the proposed new subclause for expresisons.md, "Interpolated strings," we have

> A formatting specification involves the use of a ***format string literal***, which is constructed as follows, where `N` is the number of interpolations in the *interpolated_string_expression*:
> -  If an *interpolated_regular_string_whole* or an *interpolated_verbatim_string_whole* follows the `$` sign, then the format string literal is that token.
> - Otherwise, the format string literal consists of:
>   - First the *interpolated_regular_string_start* or *interpolated_verbatim_string_start*
>   - Then for each number `I` from `0` to `N-1`:
>      - The decimal representation of `I`
>      - Then, if the corresponding *interpolation* has a *constant_expression*, a `,` (comma) followed by the decimal representation of the value of the *constant_expression*
>      - Then the *interpolated_regular_string_mid*, *interpolated_regular_string_end*, *interpolated_verbatim_string_mid* or *interpolated_verbatim_string_end* immediately following the corresponding interpolation.

***

I haven't quite gotten my head around this, but it seems to me that we should have one or more examples of these steps being applied to some non-trivial interpolated strings.

## C. Hole Content Formatting Details

Almost all the examples I've added are trivial, but here are two examples worth mentioning:

```csharp
string text = "red";
int number = 14;
$"|{ text , 8 }|"              // "|     red|"; right-justifed in width of 8
$"|{number:X}|"                 // "|E|"; uppercase hex
```
So where does a reader of the spec go to find out what can follow the comma and colon and the corresponding semantics?

At https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated I see 

> The structure of an item with an interpolation expression is as follows:
> `{<interpolationExpression>[,<alignment>][:<formatString>]}`

with a bit of discussion.

Perhaps `String.Format` is involved.

In any event, our spec currently has quite a few calls to `System.Console.Write` and `System.Console.WriteLine` that use format specifiers of the form `{x, y: z}`, which behave a *lot* like those in interpolated strings, but we *don't* explain any of them, so maybe we don't need to do that here either.

My hope is that we can punt to something in the library, such as `String.Format` (which *is* in the CLI spec) to cover this.

**Comment by BillWagner** [comment]
@jskeet 

I had in my notes to look at this for an upcoming meeting.

Looking at the history, I believe @RexJaeschke added the examples required for item "B" above before we put the standard text in this repo.

I believe this can be closed with no further action.

**Comment by jskeet** [comment]
Yes, I agree that it's fine to be closed. Would like confirmation from @RexJaeschke that he's happy for us to do so first though :)

**Comment by RexJaeschke** [comment]
I just looked at the edits I made w.r.t examples, and I agree that that aspect has been addressed.
