### ISSUE TITLE
11.8 Method group conversions requires error even if the conversion isn't used

### ISSUE THREAD

**Issue by gafter** [dotnet/csharpstandard#188]
Consider this little test program
```csharp
public class Program1
{
    delegate void MyAction<T>(T x);
 
    void Y(long x) { }
 
    void D(MyAction<int> o, short s) { }
    void D(MyAction<long> o, int i) { }
 
    void T()
    {
        D(Y, 1);
    }
}
```
The first argument in the call `D(Y, 1)` is a method group. During overload resolution, we will seek the existence of a method group conversion to see which methods are applicable.

There is an implicit conversion from argument `Y` to the first parameter of the first `D` method, according to 11.8:

> - A conversion is considered to exist if the algorithm of §12.7.6.2 produces a single best method M having the same number of parameters as `D`.
> - Even if the conversion exists, a compile-time error occurs if the selected method `M` is not compatible (§20.4) with the delegate type `D`.

There certainly is a best method, as there is only one `Y`.  But since `Y` is not compatible with the delegate type `MyAction<int>`, a compile-time error occurs.  This is even though the compiler would not even try to apply that conversion, instead selecting the other overload of `D` as the one to be called!

Actual compilers do not report this compile-time error unless the conversion is attempted to be used. This test program compiles and runs.

**Comment by jskeet** [comment]
Note to self: see if #263 fixes this.
