### ISSUE TITLE
12.2.1 Expression classifications|General

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#192]
In the list accompanying “An expression is classified as one of the following:”, v5std has

> -   A type. An expression with this classification can only appear as the left-hand side of a *member_access* (§12.7.5). In any other context, an expression classified as a type causes a compile-time error.”

while v6spec has

> *  A type. An expression with this classification can only appear as the left hand side of a *member_access* ([Member access](expressions.md#member-access)), or as an operand for the `as` operator ([The as operator](expressions.md#the-as-operator)), the `is` operator ([The is operator](expressions.md#the-is-operator)), or the `typeof` operator ([The typeof operator](expressions.md#the-typeof-operator)). In any other context, an expression classified as a type causes a compile-time error.

What to do?

**Comment by Nigel-Ecma** [comment]
By the alternative PR #250, replacing #10, the operand of `name` is a *named_entity* and not an *expression*, so it looks like there is no need for a change here if #250 is accepted.

**Comment by Nigel-Ecma** [comment]
PR #250 has been accepted (pending @jskeet removing a tuple from an example and creating a PR for v7 to put it back) so there is nothing left to do here. Will close and remove discuss tag.
