### ISSUE TITLE
Need spec text for new V6 feature "empty array for params parameter"

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#200]
See https://github.com/dotnet/csharplang/blob/master/proposals/csharp-6.0/empty-params-array.md

Can someone write up this new spec text?

**Comment by jskeet** [comment]
Assigning this one to Eric as Neal already has overload resolution - I *anticipate* this being easy enough to understand without having been in the team when it was implemented, but please shout if that's not the case.

**Comment by gafter** [comment]
Don't forget to add empty array API; see #5

**Comment by jskeet** [comment]
Discussion: we won't refer to `Array.Empty`, and we'll leave the interning as implementation-specific.
