### ISSUE TITLE
v7.x Q.s re the "ref local and returns" spec

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#214]
In Draft PR https://github.com/ECMA-TC49-TG2/csharpstandard/pull/213, I've spec'd "ref locals and returns." This issue asks some questions that might impact that spec.

## Question 1:

Given the following method declarations:

```csharp
public static int M1() { … }
public static ref int M2() { … }
public static ref readonly int M3() { … }
```

and the following ref-assignment:

```csharp
int i;
i = M1() - M2() + M3();
```

the **values** returned from each method are used to compute the result that is stored in `i`. However, `M2` and `M3` actually return a **reference** to a writeable and read-only `int`, respectively. Is there an implicit conversion going on here? That is, when one has a reference, but a value is expected, the value is taken. I ask, as my spec does *not* mention any such conversion.

## Question 2:

Given

```ANTLR
foreach_statement
    : 'foreach' '(' local_variable_type identifier 'in' expression ')' embedded_statement
    ;
```

it seems like *local_variable_type* could/should allow a `ref` or `ref readonly` prefix, as follows:

```ANTLR
foreach_statement
    : 'foreach' '(' (ref readonly?)? local_variable_type identifier 'in' expression ')' embedded_statement
    ;
```

While my compiler allows these keywords there, I was not able to get an example to compile. Can someone show me correct code examples using `ref` and `ref readonly`, so I can write text for this case?

## Question 3:

In 13.11, "The try statement," we have

```ANTLR
...
catch_clause
    :  'catch' exception_specifier?  block
    ;

exception_specifier
    : '(' type identifier? ')'
    ;
```

The compiler does *not* allow `ref` or `ref readonly` prior to *type.* Should it? That is, can we catch-by-ref?

**Comment by KalleOlaviNiemitalo** [comment]
Re question 3, I don't think catch-by-ref should be allowed. If it were allowed, I imagine it could be used for:

* Not making a copy of the caught value.
  - The `type` in `exception_specifier` must be derived from System.Exception and thus a reference type, so it's cheap to copy anyway.
* Reassigning the reference, to make a subsequent `throw;` rethrow an exception instance different from the one that was caught.
  - It is not clear how that should affect Exception.StackTrace.
  - Would need to change ECMA-335 6th ed. §II.19 (Exception handling) and §II.25.4.6 (Exception handling clauses) to describe how the catch block is marked to give it a managed pointer rather than a reference.
  - One can already use `throw` _expression_ for a similar effect.

.NET SDK 5.0.203 apparently allows returning by reference in `property_declaration` and `indexer_declaration` but not `operator_declaration`. I haven't found a rationale for that.

**Comment by KalleOlaviNiemitalo** [comment]
Re question 2:

```C#
using System;

class ForeachRefDemo
{
    static void Main()
    {
        int[] array = new int[5];

        foreach (ref int i in array.AsSpan())
        {
            i = 42;
        }

        Console.WriteLine(array[2]);
    }
}
```

Or without using Span:

```C#
using System;

class ForeachRefDemo
{
    static void Main()
    {
        int[] array = new int[5];

        foreach (ref int i in new IntArrayRefEnumerable(array))
        {
            i = 42;
        }

        Console.WriteLine(array[2]);
    }
}

struct IntArrayRefEnumerable
{
    int[] array;

    public IntArrayRefEnumerable(int[] array)
    {
        this.array = array;
    }

    public IntArrayRefEnumerator GetEnumerator() => new IntArrayRefEnumerator(this.array);
}

struct IntArrayRefEnumerator
{
    int[] array;
    int index;

    public IntArrayRefEnumerator(int[] array)
    {
        this.array = array;
        this.index = -1;
    }

    public bool MoveNext()
    {
        if (this.index < this.array.Length - 1)
        {
            this.index++;
            return true;
        }
        else
        {
            return false;
        }
    }

    public ref int Current => ref this.array[this.index];
}
```

**Comment by RexJaeschke** [comment]
Re Question 1: This is answered in 12.2.2 Values of expressions:

> Most of the constructs that involve an expression ultimately require the expression to denote a ***value***. In such cases, if the actual expression denotes a namespace, a type, a method group, or nothing, a compile-time error occurs. However, if the expression denotes a property access, an indexer access, or a variable, the value of the property, indexer, or variable is implicitly substituted:
> -   The value of a variable is simply the value currently stored in the storage location identified by the variable. A variable shall be considered definitely assigned ([§10.4](variables.md#104-definite-assignment)) before its value can be obtained, or otherwise a compile-time error occurs.
> ...

Re Question 2: Thanks, @KalleOlaviNiemitalo for the working example. I have added support for `ref readonly` to `foreach`.

Re Question 3: @KalleOlaviNiemitalo answered this. No change is needed.
