### ISSUE TITLE
Check fonts in conversion template

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#23]
Currently we appear to be using Cambria at 10 points for normal text, which isn't terribly easy to read.

**Comment by RexJaeschke** [comment]
Yes, Jon; this looks complete. Rex

**Comment by jskeet** [comment]
I should look through this set of notes again. At least some of these are now fixed.

**Comment by jskeet** [comment]
Set for C# 6 mostly so that I can go through the list again - not necessarily fixing anything that remains, but knowing what *does* still remain.

**Comment by RexJaeschke** [comment]
I'm in the process of manually editing the generated Word spec for submission to Ecma. I have a new document, "Manual-steps-to-apply-to-gen'd-Word-Spec-for-publication" that contains the steps needed, and soon this will be uploaded as a new document in folder `admin`. That document subsumes this Issue, which I'm closing. 

Once the submission has been completed, I plan to work with Jon and Bill to see which, if any, of the manual steps can be automated by the converter in future, or pushed back into markdown.
