### ISSUE TITLE
Use a consistent spelling of the ANTLR grammar fence

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#245]
While almost all ANTLR grammar block fences begin with uppercase `ANTLR`, a few (possibly in as-yet un-merged V6 [and V7] PRs) use lowercase `antlr`. Although both spellings are recognized (by the GitHub renderer and our grammar-extraction tool), Jon and I have agreed that, for consistency, we should use the uppercase approach.

We can change all lowercase occurrences to uppercase in the final stages of closing out V6.

**Comment by jskeet** [comment]
Fixed by #404.
