### ISSUE TITLE
Distinguishing between a keyword and an identifier

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#259]
[This issue arose from my work on replacing the lexer grammar rule alternatives of the form `'<...>'` in Proposal 3 of #37.] 

Grammatically, the spelling of a keyword is a (very small) proper subset of that for an identifier. (The former is a short list whose members *cannot* contain Unicode sequences; the latter is open-ended and whose members *can* contain Unicode sequences *unless* they are being used as contextual keywords.)

Ignoring any rules ANTLR might have, given the grammar we've used since V1, how does a lexer determine if the token `int`, for example, is a keyword or an identifier?

My guess is that "If a token matches the grammar rules for both *Keyword* and *Identifier*, it is a *Keyword*; however, I can't find any words in the spec to that effect. What am I missing?

With ANTLR (see book, last lines of p. 285),

> If more than one lexer rule matches the same input sequence, the priority goes to the rule occurring first in the grammar file.

This means that the ordering of lexer rules can matter. Now we *don't* discuss such ordering in the spec. What we do do is to describe rule *Identifier* (7.4.3) **before** rule *Keyword* (7.4.4), so when the grammar extractor runs, the rules are defined in that same order. As such, `int` is an *Identifier*! That doesn't sound right.

**Comment by Nigel-Ecma** [comment]
Good questions.

The old grammar rule notation didn't come with well-defined semantics, it was sort of assumed that questions like these had the "obvious" answer. It was not a grammar that would be used directly by a compiler.

Now using ANTLR we have a notation with a well-defined semantics and these questions need answers.

Those answers should come from #37 and investigations into the grammar triggered by it. I'll mark this as a dependency and add a comment in #37.

Also added #260 to the dependency group.

**Comment by RexJaeschke** [comment]
This has been addressed by PR #342.
