### ISSUE TITLE
Attribute parameter types:  The documentation claims string arrays are allowed, but they are not.

### ISSUE THREAD

**Issue by colgreen** [dotnet/csharpstandard#268]
Here [Attribute parameter types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#attribute-parameter-types)

The docs say:

> The types of positional and named parameters for an attribute class are limited to the attribute parameter types, which are:
>   * One of the following types: bool, byte, char, double, float, int, long, sbyte, short, string, uint, ulong, ushort.
>   ...
>   * Single-dimensional arrays of the above types.

The String type is listed in the first bullet point, and the docs claim we can therefore use an array of strings, but a string array is *not* allowed, producing a CS0182 compile time error:

>  "An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 336afb22-5d56-e3a4-0389-564748e9af6e
* Version Independent ID: d7c118fe-bdab-ca0a-795c-f4ece0af5562
* Content: [Attributes - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes)
* Content Source: [spec/attributes.md](https://github.com/dotnet/csharplang/blob/master/spec/attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jskeet This might also be below the bar.

**Comment by jskeet** [comment]
I'd be happy for this to be below the bar, yes. Let's ratify in the next meeting.

**Comment by jskeet** [comment]
Closing - we'll live with this.
