### ISSUE TITLE
Semantics of partial methods aren't accurately described.

### ISSUE THREAD

**Issue by geeknoid** [dotnet/csharpstandard#269]
C# 9.0 changed the semantics of partial methods, this page needs to be updated accordingly. New semantics: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/extending-partial-methods.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94b01ab-fe87-23fc-44b6-da9f3f627bd5
* Version Independent ID: a86008b1-2fdd-bbb9-3bbf-8fc8c51c1b71
* Content: [Classes - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#methods)
* Content Source: [spec/classes.md](https://github.com/dotnet/csharplang/blob/master/spec/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jskeet Well, our first 9.0 issue.

**Comment by KalleOlaviNiemitalo** [comment]
My question about an XML documentation comment on an extended partial method declaration: <https://github.com/dotnet/csharplang/discussions/4160>

**Comment by jskeet** [comment]
We should discuss how we want to handle issues like this. I'm tempted to close them on the grounds that there's no point in building up a list of issues (which is likely to be both incomplete and contain duplicates if we're not careful) for versions we know we have done yet. When we start doing C# 9, we'll look at *all* the features and create a complete set of issues - I don't think having them accumulate beforehand is likely to be helpful.

But we do need to make that clear in an issue template or README, of course. This is in no way meant to be a complaint at the issue having been filed in the first place :)

**Comment by jskeet** [comment]
Closing this now, after adding notes about issues for features in later versions of C# than we've got to so far.

(We absolutely appreciate the careful checking of what we're covering, but it's useful if you can wait until we've reached a version before filing any issues for it :)
