### ISSUE TITLE
ref-safe-to-escape rule for in parameter

### ISSUE THREAD

**Issue by gafter** [dotnet/csharpstandard#296]
Looking at

https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#method-invocation

> - For each `in` parameter of the method, if there is a corresponding expression that is an lvalue, its _ref-safe-to-escape_, otherwise the nearest enclosing scope 

This is only correct if the argument has an identity conversion to the type of the parameter. For any other type of conversion, I think it should be "nearest enclosing scope" because a copy will be made.

---
[Associated WorkItem - 52211](https://dev.azure.com/msft-skilling/Content/_workitems/edit/52211)

**Comment by BillWagner** [comment]
tagging @RexJaeschke as this is in an area you're working on now for C# 7.x

**Comment by jskeet** [comment]
Whoops - the link from PR 381 should have been to issue 269, not this one...

**Comment by jskeet** [comment]
This should be fixed by #795.

**Comment by BillWagner** [comment]
The text on Line 1181 in variables.md needs to be clarified.
