### ISSUE TITLE
(un)checked expressions as statements?

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#318]
[This came to light during checking of the grammar using Antlr]

The MS test file `AllInOneNoPreprocessor.cs` contains the code:

```
   checked
   {
      checked(++i);
   }
   unchecked
   {
      unchecked(++i);
   }
```

where *(un)checked_expression* is used as a *statement_expression*. The Standard does not allow this. Note the above is rather pointless as it is a longhand way of writing:

```
   checked { ++i }
   unchecked { ++i }
```

which *is* allowed by the Standard (and *(un)checked_statements* can nest so there is no limitation imposed by the Standard’s approach).

So should the Standard stay as it is or follow this MS test file (which implies the MS compiler supports this)?

I think it could be allowed by extending *statement_expression*:

```
   statement_expression
      : invocation_expression
      | object_creation_expression
      | assignment
      | post_increment_expression
      | post_decrement_expression
      | pre_increment_expression
      | pre_decrement_expression
      | await_expression
      | 'checked' '(' statement_expression ')'
      | 'unchecked' '(' statement_expression ')'
      ;
```

Rather than include *(un)checked_expression* the (un)checkable statement expressions are limited to just expressions allowed as statements, subroles *(un)checked_statement_expression* could be defined if preferred.

I think this is going to be an easy yes/no, though folk might like to discuss the grammar choices, so vote away and if there is support a PR can be quickly made.

**Comment by KalleOlaviNiemitalo** [comment]
These compilers give error CS0201 for `checked(i++);`:

- "Microsoft (R) Visual C# Compiler version 4.8.4084.0 for C# 5" from .NET Framework 4.8
- "Microsoft (R) Visual C# Compiler version 2.10.0.0 (b9fb1610)" from Visual Studio 2017
- "Microsoft (R) Visual C# Compiler version 3.9.0-6.21160.10 (59eedc33)" from .NET SDK 5.0.203

**Comment by KalleOlaviNiemitalo** [comment]
> The MS test file AllInOneNoPreprocessor.cs

If you mean [AllInOneNoPreprocessor.cs in antlr/grammars-v4](<https://github.com/antlr/grammars-v4/blob/5e9e8da993d7f576cb8dac269f6e9d4ecc33d96d/csharp/examples/AllInOneNoPreprocessor.cs#L223-L230>), then [CSharpParser.g4](https://github.com/antlr/grammars-v4/blob/5e9e8da993d7f576cb8dac269f6e9d4ecc33d96d/csharp/CSharpParser.g4#L438-L440) just allows all kinds of expressions in `simple_embedded_statement`.

**Comment by svick** [comment]
@KalleOlaviNiemitalo [That file originally came from the roslyn repo.](https://github.com/dotnet/roslyn/blob/315c2e1/src/Compilers/Test/Core/TestResource.resx#L405-L408)

**Comment by Nigel-Ecma** [comment]
This has been determined to be a test on how lenient the *parser* phase of the compiler is (subsequent semantic analysis should reject it). No action required.
