### ISSUE TITLE
Add a standalone TOC file

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#329]
I'd like to update the section numbering tool to create a standalone toc.md file in the spec folder (in addition to updating the readme.md file in this repo).

As we complete the features for C# 6.0, I'd like to publish the draft standard text on docs.microsoft.com instead of the Microsoft spec from the [csharplang](https://github.com/dotnet/csharplang/tree/main/spec) repo. The format for the updated TOC is much nicer, so would be a great detailed table of contents.

**Comment by BillWagner** [comment]
@jskeet If we can approve this prior to our next meeting, I'll have the code ready by then. Otherwise, let's discuss when we next meet.

**Comment by jskeet** [comment]
Will have a look in the morning

**Comment by jskeet** [comment]
Okay, this definitely sounds good - several times I've wanted to get to the TOC and gone to the standard directory, only to find it's not there.

One question though: would it make sense to still call it README.md just for the sake of GitHub displaying it automatically?
