### ISSUE TITLE
Strange reference to Section 12.7.3 in §C.3 Expression<TDelegate>.Compile()

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#341]
In draft-v6, Section C.3 "Standard Library Types not defined in ISO/IEC 23271" includes this reference to Section 12.7.3: <https://github.com/dotnet/csharpstandard/blob/331aae414c0955eb460bd1cbdbcb94792ba83845/standard/standard-library.md#L568-L577>

However, [12.7.3 Simple names](https://github.com/dotnet/csharpstandard/blob/331aae414c0955eb460bd1cbdbcb94792ba83845/standard/expressions.md#1273-simple-names) does not mention "delegate". Perhaps the reference should be to some other section.

**Comment by KalleOlaviNiemitalo** [comment]
The 5th edition of ECMA-334 has the same error. The 4th edition does not mention expression trees.

I think the reference was intended to mean [§11.7.3 Evaluation of anonymous function conversions to expression tree types](https://github.com/dotnet/csharpstandard/blob/331aae414c0955eb460bd1cbdbcb94792ba83845/standard/conversions.md#1173-evaluation-of-anonymous-function-conversions-to-expression-tree-types).  However, that section does not include any details on supported delegate types; instead, there is text saying it's all implementation-defined. It might thus be best to delete the comment from §C.3 altogether.

[§9.6 Expression tree types](https://github.com/dotnet/csharpstandard/blob/331aae414c0955eb460bd1cbdbcb94792ba83845/standard/types.md#96-expression-tree-types) likewise says "These exceptions are detailed in §11.7.3" even though there are no details there.

**Comment by jskeet** [comment]
Thanks - will have a look at this before the next meeting.
