### ISSUE TITLE
v7.x Q.s re Generalized Async Methods

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#345]
My notes re the addition of this feature are contained in the attached Word document ([Generalized_async_return_types.docx](https://github.com/dotnet/csharpstandard/files/6733946/Generalized_async_return_types.docx)). While I have come up with quite a few specific edits, I really don’t have enough to make a decent Draft PR. All the things marked in red or yellow need attention.

**Comment by jskeet** [comment]
(Labeling this as a feature in that it's a request for more details *for* a feature.)

**Comment by gafter** [comment]
@ljw1004 Your help on this issue would be most welcome!

**Comment by RexJaeschke** [comment]
The points raised by the referred-to Word document have either been resolved or logged as comments in PR #556 (which contains the proposed changes), so this Issue can be closed.
