### ISSUE TITLE
Standard Library Types Incorrect Division Into §C.2 and §C.3

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#385]
The Standard Library types required by C# are split into those in the CLI ISO Standard (§C.2) and those without any Standard definition (§C.3). While working on interpolated strings it was found that some of the types it uses were incorrectly in §C.3 when they are in fact in the ISO Standard.

This suggests that §C.2 and §C.3 are out of sync with the latest CLI ISO Standard from 2012. These clauses need to be reviewed to ensure each type is in the right clause.

**Comment by Nigel-Ecma** [comment]
FYI: At the time of writing changes proposed as part of the work on the PR for interpolated strings:

- `System.String.Format` – this was included in §C.2 with a *Note* attached stating it is not actually in the ISO Standard. It is, the *Note* has been removed.
- `System.IFormattable` – this was included in §C.3 when it is the ISO Standard. Moved to §C.2.

These changes are in a PR which at the time of writing is still in pre-draft stage and other changes in this are may be made.

**Comment by jskeet** [comment]
Jon to download the XML file from https://www.ecma-international.org/publications-and-standards/standards/ecma-335/ and work out what needs to change.

**Comment by RexJaeschke** [comment]
@jskeet I have a suggestion re these sections. Also, let me know if you want any help with this, as I have the time.

In C.2, we have each type inside its own namespace. Why not put all the types for a given namespace inside a single namespace declaration, in alphabetical order? Not only will this reduce the number of lines needed, it will force all the types for any given namespaces to be gathered together, (Currently, they are interspersed, with each new contribution probably added to the end.)  For example:

```csharp
namespace System
{
    public class ArgumentException : SystemException
    {
        public ArgumentException ();
        public ArgumentException (string message);
        public ArgumentException (string message, Exception innerException);
    }
}

namespace System
{
    public delegate void Action ();
}
...
```

becomes

```csharp
namespace System
{
    public delegate void Action ();

    public class ArgumentException : SystemException
    {
        public ArgumentException ();
        public ArgumentException (string message);
        public ArgumentException (string message, Exception innerException);
    }
}
...
```

**Comment by jskeet** [comment]
I'd certainly be fine with putting everything from a single namespace in one declaration, yes. If you have the time to create a PR for this, that would be great.

**Comment by jskeet** [comment]
@RexJaeschke: I believe you said you had the XML files that contained the ECMA-335 version... currently https://www.ecma-international.org/ is failing for me, so I can't make progress on this otherwise. Please could you email them to me if you have them?

**Comment by jskeet** [comment]
Scratch that - I've got the file now. Will take a look now.

**Comment by jskeet** [comment]
The [attached file](https://github.com/dotnet/csharpstandard/files/8078938/cli-types.txt) has the fully-qualified names of all types in the CLI XML document.

§C.3 contains the following types:

- System.FormattableString
- System.Linq.Expressions.Expression<TDelegate>
- System.Runtime.CompilerServices.CallerFilePathAttribute
- System.Runtime.CompilerServices.CallerLineNumberAttribute
- System.Runtime.CompilerServices.CallerMemberNameAttribute
- System.Runtime.CompilerServices.FormattableStringFactory
- System.Runtime.CompilerServices.ICriticalNotifyCompletion
- System.Runtime.CompilerServices.INotifyCompletion
- System.Runtime.CompilerServices.TaskAwaiter
- System.Runtime.CompilerServices.TaskAwaiter&lt;T&gt;
- System.Threading.Tasks.Task
- System.Threading.Tasks.Task&lt;TResult&gt;

None of these types is part of the CLI spec. I assume that Nigel has already fixed the issues he found when writing up string interpolation. I haven't looked in the other direction - I expect that every type in §C.2 really *is* in the standard.

Proposal: close with no further action. (But probably do this as an exercise before each release...)

**Comment by jskeet** [comment]
Closing as discussed in the meeting.
