### ISSUE TITLE
Delegate removal should not require *proper* contiguous sublist

### ISSUE THREAD

**Issue by svick** [dotnet/csharpstandard#389]
[The spec says the following about delegate removal:](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#1296-subtraction-operator)

> If the first operand is `null`, the result of the operation is `null`. Otherwise, if the second operand is `null`, then the result of the operation is the value of the first operand. Otherwise, both operands represent invocation lists (§20.2) having one or more entries, and the result is a new invocation list consisting of the first operand's list with the second operand's entries removed from it, provided the second operand’s list is a proper contiguous sublist of the first's. (To determine sublist equality, corresponding entries are compared as for the delegate equality operator (§12.11.9).) Otherwise, the result is the value of the left operand. Neither of the operands' lists is changed in the process. If the second operand's list matches multiple sublists of contiguous entries in the first operand's list, the right-most matching sublist of contiguous entries is removed. If removal results in an empty list, the result is `null`.

My problem is with the phrase "proper contiguous sublist", specifically the "proper" part. As I understand it (and correct me if I'm wrong, since I'm not a native English speaker), this would imply that if the two lists are the same, this condition is not satisfied and the result should be the left operand. This is clearly nonsense (especially since it would mean that the last sentence about `null` would never apply) and it's not what the compiler does.

So, should the word "proper" be removed from the paragraph above?

**Comment by jskeet** [comment]
We'll try to discuss this next week.

**Comment by RexJaeschke** [comment]
Thanks @svick.

In the very early days of TG2, I worked on the words in this subclause and provided the example. On reading them now, here are my observations:

1. According to Wiktionary, the term *proper* when used in the context of *proper subset* **excludes** the possibility if one list being contained within another, identical list, so the use of *proper* seems to be inappropriate, or at least, misleading.
1. In the case of having two invocation lists, it is misleading to say that “the result is a new invocation list consisting of …” when, in fact, the result is `null` when the lists are the same. While we do say that near the end, that’s too far away from this initial claim to effectively negate it.
1. Rewriting the text as a series of (nested) bullets makes it easier to read.
1. Extending and rearranging the example to show all the options, in order of the corresponding bullets, reinforces the text.

Here then is my proposed replacement:

> The semantics are as follows:
> - If the first operand is `null`, the result of the operation is `null`.
> - Otherwise, if the second operand is `null`, then the result of the operation is the value of the first operand.
> - Otherwise, both operands represent invocation lists ([§20.2](delegates.md#202-delegate-declarations)).
>   - If the lists compare equal, as determined by the delegate equality operator ([§12.11.9](expressions.md#12119-delegate-equality-operators)), the result of the operation is `null`.
>   - Otherwise, the result of the operation is a new invocation list consisting of the first operand's list with the second operand's entries removed from it, provided the second operand’s list is a sublist of the first's. (To determine sublist equality, corresponding entries are compared as for the delegate equality operator.) If the second operand's list matches multiple sublists of contiguous entries in the first operand's list, the right-most matching sublist of contiguous entries is removed.
>   - Otherwise, the result of the operation is the value of the left operand.

> Neither of the operands' lists (if any) is changed in the process. 

> *Example*:
> ```csharp
> delegate void D(int x);
> class C
> {
> 	public static void M1(int i) { /* ... */ }
> 	public static void M2(int i) { /* ... */ }
> }
> class Test
> {
>    static void Main() {
>       D cd1 = new D(C.M1);
>       D cd2 = new D(C.M2);
>       D cd3 = null;                   // null
>       cd3 -= cd1;                     // => null
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= null;                    // => M1 + M2 + M2 + M1
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= cd1 + cd2 + cd2 + cd1;   // => null
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= cd1 + cd2;               // => M2 + M1
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= cd2 + cd2;               // => M1 + M1
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= cd2 + cd1;               // => M1 + M2
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= cd1;                     // => M1 + M2 + M2
>       cd3 = cd1 + cd2 + cd2 + cd1;    // M1 + M2 + M2 + M1
>       cd3 -= cd1 + cd1;               // => M1 + M2 + M2 + M1
>    }
> }
> ```
> *end example*

**Comment by svick** [comment]
@RexJaeschke Thanks for looking into this. I agree that your replacement is better, though I have one small nit:

> the right-most matching sublist of contiguous entries is removed

I think it would be clearer to say "last matching sublist" instead of "right-most", since a list is naturally ordered first-to-last, but I would say ordering left-to-right is technically not specified. (Also, it may be confusing to people who use a right-to-left language, I'm not sure.)

**Comment by RexJaeschke** [comment]
Thanks, @svick. Putting on my eccentric implementer's hat, what if I search the list back-to-front, instead of front-to-back? In that case, the last-matching sublist could be at the front rather than at the back!

How about we say "**positionally** last matching sublist"?

**Comment by svick** [comment]
@RexJaeschke Personally, I think that's unnecessary. You can search the list in whatever order you want, but that doesn't change the inherent order of a list, and I think it's clear that an unqualified "last" is talking about that order.

But I'm fine with the wording you suggest too.

**Comment by jskeet** [comment]
Rex to create a PR.

**Comment by RexJaeschke** [comment]
Handled by PR #407.
