### ISSUE TITLE
Word converter: using | instead of :

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#393]
Take the start of `types.md`:

    ```ANTLR
    type
        : reference_type
        | value_type
        | type_parameter
        | pointer_type     // unsafe code support
        ;
    ```

This is *rendered* with a | instead of a : in the first line.

I'm assuming that's a problem?

**Comment by jskeet** [comment]
Ah, no... it's actually rendered as:

```text
type:
	| reference_type
	| value_type
	| type_parameter
	| pointer_type          // unsafe code support
	;
```

Note the colon at the end of `type`. So I assume this isn't actually wrong, just a different way of displaying it.

I think it should be feasible to render it more like the original, but we don't have the information about how the original was actually written... so we'll have to assume all productions are written that way.

Is that reasonable?

**Comment by Nigel-Ecma** [comment]
Correct, that is most definitely a problem.

**Comment by Nigel-Ecma** [comment]
Replied too soon…

Sorry, still a problem. The ANTLR syntax is:

<name> ‘:' <definition> ( ‘|' <definition> )* ‘;’

Whether it is rendered as:

type:
	reference_type
	| value_type
	…

or

type
	: reference_type
	| value_type
	…

or even

type : reference_type | value_type …

doesn’t matter (though the last one would end up with very long lines in places!).

This syntax applies to all ANTLR rules, there are no double-colons as in the old grammar language, so the first delimiter is always a colon, middle ones always a vertical bar, and the end always a semi-colon.

**Comment by RexJaeschke** [comment]
Style-wise, I'm thinking we took guidance from Lucien's original ANTLR grammar for V5 or V6. Rule names are on their own line with no colon. However, when I added the all-uppercase rule names as synonyms for single tokens, such rules are completely contained on one line.

Looking at the ANTLR textbook, it *never* uses "rule-name : new-line".

**Comment by jskeet** [comment]
Righto - I think I can retain that format reasonably easily. Hopefully I'll have a PR by the end of the day.
