### ISSUE TITLE
Annex headings are incorrect

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#398]
The TOC is okay, but the annexes themselves have things like "23.10" - the sections have continued to be numbered from the end of the main text.

**Comment by BillWagner** [comment]
I'll look at the section renumbering tool to see if it's the culprit here.

Update: I looked at the markdown source. That is correct now. Is this issue related to the Word converter output only?

**Comment by jskeet** [comment]
I don't think it is - the Markdown looks okay to me. I suspect we need to basically tell Word that we know better than it does...

**Comment by jskeet** [comment]
Hmm. I *suspect* we need to basically tell Word to start renumbering with "A", "B", "C" etc. That's not as easy as I'd like it to be though :(

Assigning to Rex for ideas...

**Comment by RexJaeschke** [comment]
Up to and including V5, when we used Word, styles "Heading 1," "Heading 2," and so on were used for clauses, and clauses were numbered starting at 1. Styles "Appendix 1," "Appendix 2," and so on were used for Annexes, and annexes were "lettered" starting at A. (If/when we eventually submit to ISO, they required Annex headers to be multi-lined with soft-returns between lines. ISO also requires the Bibliography to be like an annex but *not* lettered like an annex!) 

I don't know how the generator works w.r.t styles. If it works from a starter Word template, perhaps we can get these annex styles in there and emit text using them.

Given the small number of annexes, if it's too difficult to automate this, I can do it manually. BTW, I see that we already use letters in the md annexes.

**Comment by jskeet** [comment]
I've set this as the C# 6 milestone, but mostly to remind Rex to perform manual changes. I don't *think* we're going to be able to fix this in the converter any time soon - at least I won't. (Bill may have more luck.)

**Comment by BillWagner** [comment]
Adding myself as an assignee to make sure I look at the word converter to see if it's easy.

**Comment by RexJaeschke** [comment]
I'm in the process of manually editing the generated Word spec for submission to Ecma. I have a new document, "Manual-steps-to-apply-to-gen'd-Word-Spec-for-publication" that contains the steps needed, and soon this will be uploaded as a new document in folder `admin`. That document subsumes this Issue, which I'm closing. 

Once the submission has been completed, I plan to work with Jon and Bill to see which, if any, of the manual steps can be automated by the converter in future, or pushed back into markdown.
