### ISSUE TITLE
Revising "4 Acronyms and abbreviations"

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#425]
When we submit V6 to Ecma in April, this will be our first time starting with an md base and generating from that the Word rendering we submit. As such, I'm working with Jon to automate as much of that process as is reasonably possible. (That said, it is almost certain I will have to make a number of manual changes to the resulting Word document.) At the same time, I'm looking at our spec from the point of view of eventually submitting it to ISO (but not for V6), which has *many* requirements, more than a few of which we do *not* follow.

While reviewing "4 Acronyms and abbreviations," I came to the following conclusions. Nothing is broken, per se; this is just some editorial housekeeping.

## **Recommendation 1** 

We strike the following:

> The following acronyms and abbreviations are used throughout this specification:
> BCL --- Base Class Library, which provides types to represent the built-in data types of the CLI, simple file access, custom attributes, security attributes, string manipulation, formatting, streams, and collections.
> CLI --- Common Language Infrastructure
> CLS --- Common Language Specification
> IEC --- the International Electrotechnical Commission
> IEEE --- the Institute of Electrical and Electronics Engineers
> ISO --- the International Organization for Standardization

BCL and CLI are explained in "Normative references;" CLS is never used; and IEC, IEEE, and ISO are well-known in the IT world, so no need to mention them here.

## **Recommendation 2**

We move the following:

> The name C# is pronounced "C Sharp".
> The name C# is written as the LATIN CAPITAL LETTER C (U+0043) followed by the NUMBER SIGN # (U+0023).

to the end of "Introduction."

## **Recommendation 3** 

We change

> ... Throughout this specification, these types will appear as the fully qualified name, omitting the global namespace qualifier, or as a simple unqualified type name, omitting the namespace. ...

to

> ... Throughout this specification, these types appear as either the fully qualified name; with the global namespace qualifier omitted; or as a simple unqualified type name, with the namespace omitted as well. ...

## **Recommendation 4**

We change the clause title to “Library type name abbreviations.” We can leave the file name as is, so we don’t have to change any tooling.

I even thought about striking this clause and moving its content to a new section in Type.md following 9.1. As "Types" is the first substantive clause, this topic would not be out of place there.

## **Recommendation 5** 

We strike the Clause delimiter lines **This clause is informative.** and **End of informative text.**, as all the remaining contents are normative.

**Comment by jskeet** [comment]
If we can drop a whole clause by moving the remaining bits to types.md, that sounds like a win to me. Everything before "Lexical structure" always feels somewhat like fluff...

**Comment by RexJaeschke** [comment]
On today's call, we agreed to Recommendations 1, 2, 3, and 5.

Re Recommendation 4, we agreed to move this list out of this clause, but rather than to 9 Types|9.1 General, as these are all library types, how about putting it "right out of the way" in the Library Annex, C? Rex will look into that, and perhaps craft a new Note to be added at the first place we use an abbreviated name from this list. He'll make a PR to do this, and that leaves the Clause 4 in existence, but empty, while Bill checks his tooling to handle the deletion of a whole clause.

**Comment by RexJaeschke** [comment]
Re Recommendation 4, I moved the bullet list of fully qualified names to a new subclause at the end of Annex C. And I added a fwd pointer to that location at the end of 9.1.
