### ISSUE TITLE
Word converter: List items in notes/examples are badly formatted

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#435]
The end of 9.3.5 has a particularly thorny note, containing a list which itself contains an example. We basically don't format it properly at all.
We may be able to simplify that note a little, but we should definitely do a *better* job of supporting lists in notes.

**Comment by jskeet** [comment]
This is also a problem in 18.6.2 (Explicit interface member implementations)

**Comment by jskeet** [comment]
For C# 6 we should see if we can work out why this is happening, so we can find all the occurrences either manually or via warnings.

**Comment by BillWagner** [comment]
Adding me as assignee to remind myself to take a look.

**Comment by jskeet** [comment]
I haven't checked, but I strongly suspect that the numbered list in 6.4.3 (Identifiers) is broken too.

**Comment by jskeet** [comment]
Explicit interface implementations: the list was invalid due to missing a blank line. (This isn't actually spotted in the crude detection in #509, but is fixed there.)

6.4.3 is indeed broken, and half-fixed in #509. But it contains a *nested* list which has the right style of bullet, but incorrect indentation.

8.3.5 is fixed in #509.

Leaving this issue open for now as the indentation of lists in notes is broken.
