### ISSUE TITLE
Word converter: detect lists without a blank line before them

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#436]
In section 9.7 (the dynamic type) there is a list preceded by "Because of this equivalence, the following holds:"

There's no blank line after that sentence - it goes straight into a list. The Word converter doesn't pick up on that being a list.

**Comment by jskeet** [comment]
Need to check/fix this before C# 6.

**Comment by BillWagner** [comment]
@jskeet lists should have a blank line above and below the list. Depending on the status of the markdown converter, we could turn on markdown lint and find those instances.

**Comment by jskeet** [comment]
+1 to spotting it externally rather than having to change the Word converter :)

**Comment by jskeet** [comment]
It turns out we have 158 of these issues. Yikes.

**Comment by jskeet** [comment]
Ah, it's not quite that bad... we need to handle being in nested lists as well. This is going to be ugly...
