### ISSUE TITLE
Word converter: code block in list items not recognized

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#440]
12.9.2 has "Integer multiplication" and "Floating-point multiplication" and the code blocks aren't formatted correctly. The equivalent in 12.9.3 seems okay though...

**Comment by jskeet** [comment]
Need to investigate again before C# 6.

**Comment by BillWagner** [comment]
adding myself as an assignee.  I'll see if I can replicate this behavior in a test when I add the test harness.

**Comment by jskeet** [comment]
Now that I've got into how we can test this, I'm having a go...

**Comment by jskeet** [comment]
Okay, the problem appears to be in the MarkdownParser. My test case is:

~~~text
- Here is some code:
  ```csharp
  int x = 1;
  int y = x + 1;
  ```
~~~

That parses as:

- ListBlock
  - Literal ("Here is some code:")
  - InlineCode ("csharpint x = 1;int y = x + 1;")

We're on quite an old version of FSharp.Formatting - I'll see if updating that helps...

**Comment by BillWagner** [comment]
> We're on quite an old version of FSharp.Formatting - I'll see if updating that helps...

Warning:  I tried this once, just snapping to the latest version. There were several breaking changes in that library.

**Comment by jskeet** [comment]
> Warning: I tried this once, just snapping to the latest version. There were several breaking changes in that library.

Yup. I've managed to update the library (although I had to *downgrade* FSharp.Core to 5.0.2) and fix up all the compile-time errors. It still does generate a Word document... but that doesn't fix this particular issue. (It might fix others.)

I'm looking into whether any parse options can help us...

**Comment by jskeet** [comment]
Nope, it looks like the only parse options are ParseCodeAsOther, ParseNonCodeAsOther, AllowYamlFrontMatter - none of which sound promising here.

A few options:

- Try to fix the parser (!)
- Detect the issue and try to effectively "recreate" the code block
- Find all occurrences in the spec and rewrite them to avoid having code blocks in lists
- Flag and fix manually after word conversion

It's quite easy to find all of these - just look for "csharp" in the Word document. Other than one email address, they're all examples of code blocks in list items...

**Comment by jskeet** [comment]
Detecting it and fixing it might not actually be too hard... we still have the line breaks. Will give that a go.

Will keep the code I've got that updates the Markdown parser version though, as a separate branch - we may well want to do that anyway.
