### ISSUE TITLE
Word converter: paragraph after table in list not handled properly

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#441]
In 12.9.2 (multiplication operator) there's a table that's expected to be in a list, followed by a paragraph. The paragraph should be part of the list - followed by the next list item beginning "Decimal multiplication"

The Markdown isn't quite right here anyway, but after trying a few things I believe we'll still need more work to get it to format appropriately in Word. (Or we could rearrange the Markdown...)

**Comment by jskeet** [comment]
We need to do *something* here - that may be rearranging the Markdown, or it may be fixing the tooling, but it needs to be sorted out for C#6.

**Comment by BillWagner** [comment]
Adding myself as an assignee to remind myself to take a look at the markdown and see what options we have.

**Comment by jskeet** [comment]
Not sure that this really needs to be blocking. It's not ideal, but it's not horrific as-is.

**Comment by jskeet** [comment]
This is fixable without too much hassle. There's a prototype in #512. I'll fix it up when other PRs have been merged.
