### ISSUE TITLE
Tab characters in the markdown

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#450]
At the time of writing there are 29 tab characters spread across the files: delegates.md, documentation-comments.md, enums.md and expressions.md. Many, but not all, are in code blocks and may exist due to copy’n’paste. They may not produce the expected results, recommend removing them.

*Note: Some of these were discovered while processing the markdown, they broke the markdown parser (Markdig) in use…*

**Comment by jskeet** [comment]
Absolutely agree. I thought I'd removed them all recently, but either my memory is failing me or my tooling is!

**Comment by Nigel-Ecma** [comment]
Maybe it’s my copy which dates before your fixes. I’ll check tomorrow and close the issue if they’re gone.

**Comment by jskeet** [comment]
This was the commit that removed them:

https://github.com/dotnet/csharpstandard/commit/89f99c9fd0bac4abaa37197670a7e860d3420dab

**Comment by Nigel-Ecma** [comment]
Jon has fixed them all already, closing with thanks :-)
