### ISSUE TITLE
Configure actions to validate updates to the standard, perform automatic standard updates

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#46]
There are three tools that should run on each PR to validate any changes. These should also run when a PR is merged to the default branch to update the standard. Two of the tools edit the standard text, and therefore should only run when the default branch is updated.

The tools are:

- **Word Converter**: This tool processes all the markdown and produces a Word document for the committee to submit to standards bodies. It does not modify any of the markdown text. It can run on each PR, and when a PR is merged to the default branch.
- **Grammar extractor**: This tool extracts all the ANTLR grammar from each chapter of the spec to create the text in Annex A. It could run on each PR to create an updated Annex. It would also need to be run on the default branch after any PR is merged into the default branch. A dry-run option is nice, but not necessary.
- **Section renumber**: This tool renumbers all clauses in the standard. It also updates any links to clauses whose number may have changed due to additions, deletions, or moving clauses. Finally, it updates the README.MD with a new TOC. This should run on each PR to validate any new reference links, or new clause additions. However, on each PR it should run in the `--dry-run` mode so that it doesn't update any sections. After a PR is merged into the default branch, this tool should run in its write mode to update the standard text.

We believe these tools also imply that we should set branch protection that any source branch for a PR should be up to date with the default branch before merging into the default branch. This would mean these tools could run before merging, but the section renumbering should run in dry-run mode until a PR is ready to merge (meaning it has been approved). I think a GitHub action can be configured to run on approval, or on adding a label for "ready to merge".

**Comment by jskeet** [comment]
@BillWagner Can we close this now? I think you've implemented it all...

**Comment by BillWagner** [comment]
Yes. Closing.
