### ISSUE TITLE
Inconsistent use of formatting for kinds of accessors

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#464]
The text "get accessor" is sometimes set as "`get` accessor," although the two appear to represent the same thing. Here's a summary of what I found in the md files:

Text | Uses a code fence | No code fence
---- | ---------- | ---------------
get accessor    | 28 | 10
set accessor    | 39 | 18
add accessor   | 2  | 0
remove accessor | 4 | 3

BTW, separately, the term "getter" (sometimes with the suffix "-only")---without a code fence---occurs 5 times. "setter" is never used.

The solution is not quite a "global" pattern edit, as we have "`get` and `set` accessors" (vs. `get` and `set` tokens). Of course, many occurrences of `get` and `set` need to stay fenced.

BTW, V9 will add an `init` accessor, so it will be good to clean up this inconsistent use.

@jskeet, @BillWagner, as this is a relatively simple fix, I can do it for V6. I propose removing the fence from *all* instances that are *not* referring to the spelling of the tokens. (Note that some unfenced instances are in code comments, and we certainly don't want to add fences to them!)

**Comment by jskeet** [comment]
Yup, I'd be fine with that.

**Comment by BillWagner** [comment]
Thanks @RexJaeschke 

I agree, this is the right plan.
