### ISSUE TITLE
Undocumented Exception Type: RuntimeBinderException

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#475]
Consider the following code:

```csharp
static void M(dynamic d)
{
    var v = d >> 2;
}
```

When `M` is called with an argument of type `double`, the following results:

```output
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '>>' cannot be applied
   to operands of type 'double' and 'int'
```

The obvious solution is to mention this exception, and as it is *not* part of the CLI spec, to put it in the appropriate place in our library annex.

However, this type's namespace is `Microsoft.CSharp` not `System`, and neither our spec nor the CLI spec mention MS-specific names. Of course, we could simply spec it as it exists. The reason for pause here is that when I was editor of the XPS (XML Paper Specification) spec, that had an XML namespace of `Microsoft`, and some members of that committee (TC46) were concerned that if Ecma was to Fast Track that spec to ISO/IEC JTC/1, having a company name baked in there likely would be a red flag w.r.t getting NO votes. So, from that perspective, it's worth at least some discussion.

Thinking aloud here, could we hide this behind some sort of non-contentious namespace alias?

@jskeet I've pinged you, as I added the V6 milestone, but, frankly, if this didn't get resolved until a future version, that would be fine with me.

**Comment by KalleOlaviNiemitalo** [comment]
[8.2.4](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/types.md#824-the-dynamic-type) says an exception is thrown:

<https://github.com/dotnet/csharpstandard/blob/770f26d65e97d4fda6ea5ddc44beaa35292a65c2/standard/types.md#L102-L104>

Throwing a Microsoft.CSharp.RuntimeBinder.RuntimeBinderException seems a valid implementation of this. Why should the standard specify the type of the exception?

**Comment by RexJaeschke** [comment]
The passage you cite describes the general situation; it does *not* discuss specific kinds of problems that might cause such an exception. From a standard's point of view, the text 

> Instead, an exception will be thrown ...

is interpreted as

> Instead, an **unspecified type of** exception will be thrown ...

Of course, that precludes the ability for one to write a portable program to catch such exceptions; one simply doesn't know the exception type! And one should *never* rely on the outcome of unspecified behavior, as it's not required to be reproducible from one execution to the next! If the behavior were implementation-defined, one could rely on that for a given implementation, but not portably.

As a parallel, consider the places in the spec where we say, "a `System.NullReferenceException` is thrown" or "a `System.IndexOutOfRangeException` is thrown." Clearly, programmers appreciate that specificity. Imagine if we'd said "an unspecified exception is thrown" instead in each of these cases?

So, I think the question is, "Do we want programs to be able to catch this exception using portable code?" If not, do we at least want it to be implementation-defined rather than implicitly unspecified, so that for a given implementation it's predictable?

**Comment by KalleOlaviNiemitalo** [comment]
Do existing implementations ensure a specific exception type if dynamic binding fails on a _dynamic object_?

**Comment by jskeet** [comment]
Decided not to block C# 6 for this. Will revisit.

**Comment by RexJaeschke** [comment]
A quick look at expressions.md shows 17 occurrence of "binding-time error," each leaving unspecified as to what error is reported (or even how). So it's probably not useful to specify just one of them now.

**Comment by jskeet** [comment]
Closing as no action required.
