### ISSUE TITLE
How do we describe enums in generic types?

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#482]
This was raised in #480.

Consider:

```csharp
public class C<T>
{
    public enum E { Xyz }
}
```

That's entirely valid, and `C<string>.E` and `C<int>.E` are different types... even though an enum declaration itself can't have type parameters.

Is it reasonable to consider the declaration of `C<>.E` to be a "generic enum declaration"?

**Comment by Nigel-Ecma** [comment]
I'll offer “No” – it’s a non-generic member of a generic type.
Disclaimer: I haven’t looked into the implications for the Standard text either way.

**Comment by jskeet** [comment]
That would be inconsistent with:

```csharp
public class C<T>
{
    public class D {}
}
```

... where D is described in 14.2.1 as a generic class declaration.

**Comment by Nigel-Ecma** [comment]
It would be inconsistent with §15.2.1 as an enum is a value type aka struct. But…

- §14.2.1 says classes inside generic classes are also generic
- §15.2.1 says structs inside generic structs are also generic
- But neither says anything about a struct/class nested inside of a generic class/struct…

Can meet worms ;-)

**Comment by KalleOlaviNiemitalo** [comment]
[14.3.9.7 Nested types in generic classes](https://github.com/dotnet/csharpstandard/blob/53e081b393ea33d9a8b3dbe955ff50984ba09ab9/standard/classes.md#14397-nested-types-in-generic-classes) says

<https://github.com/dotnet/csharpstandard/blob/53e081b393ea33d9a8b3dbe955ff50984ba09ab9/standard/classes.md#L1100>

So yeah, it's a generic enum type declaration. I suggest linking from all the recently added generic-type paragraphs to 14.3.9.7 and adding a similar paragraph for enums.

**Comment by jskeet** [comment]
Will fix this, both in terms of enums and in terms of making it "any type within any generic type" in 14.2.1 and 15.2.1.

**Comment by jskeet** [comment]
@Nigel-Ecma: Both 14.2.1 and 15.2.1 *do* talk about a struct/class nested inside a generic class/struct, as far as I can see:

From 14.2.1:

> Additionally, any class nested inside a generic class declaration or a generic struct declaration is itself a generic class declaration, since type arguments for the containing type shall be supplied to create a constructed type.

From 15.2.1:

> A struct declaration that supplies a *type_parameter_list* is a generic struct declaration. Additionally, any struct nested inside a generic class declaration or a generic struct declaration is itself a generic struct declaration, since type arguments for the containing type shall be supplied to create a constructed type.

Have I misunderstood your concern?

**Comment by Nigel-Ecma** [comment]
@jskeet – You haven’t misunderstood, I obviously wasn’t reading the version I thought I was, and I double checked because I didn’t quite believe we’d let such a simple error stand. So mea culpa, both those clauses are correct in this regard and have been for quite some time (at least 7 years!) in the Standard.
