### ISSUE TITLE
Style: "new" modifier before anything else?

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#486]
I'm just editing classes.md, and while we put `override` and `virtual` after the access modifier, we put `new` before it:

```csharp
public virtual void F() {}
new private void F() {} 
public override void F() {}
```

This looks odd to me - I'd prefer `private new void F()`.

Thoughts?

**Comment by RexJaeschke** [comment]
I too prefer the accessibility modifier to come first.

I found three places using the current approach:

basic-concepts.md:>     new private static void F() {} // Hides Base.F in Derived only
classes.md:>     new private void F() {} // Hides A.F within body of B
classes.md:>     new protected int Count {

**Comment by BillWagner** [comment]
I'd also prefer the access modifier first.

**Comment by jskeet** [comment]
Righto - I'll try to identify all occurrences and fix them tomorrow or next week.

**Comment by jskeet** [comment]
Note to self: `grep "   new p" *.md` finds 13 occurrences.

**Comment by Youssef1313** [comment]
- classes.md
    - 14.3.9.4 Hiding
    - 14.3.10.2 Member names reserved for properties
    - 14.6.4 Virtual methods
    - 14.6.5 Override methods
    - 14.7.3 Accessors
    - 14.7.5 Accessibility

- interfaces.md
    - 17.6.5 Interface mapping
    - 17.6.6 Interface implementation inheritance

- basic-concepts.md
    - 7.7.2.3 Hiding through inheritance

These are the sections which have occurrences (hopefully all of them) per my searching.
