### ISSUE TITLE
Method group conversion existence and compatibility is inconsistent

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#552]
(Conversions) 10.8 starts:

> An implicit conversion exists from a method group ([§11.2](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#112-expression-classifications)) to a compatible delegate type ([§19.4](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/delegates.md#194-delegate-compatibility)).

But later we see:

> Note that the existence of an implicit conversion from E to D does not guarantee that the compile-time application of the conversion will succeed without error.

and

> Even if the conversion exists, a compile-time error occurs if the selected method M is not compatible ([§19.4](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/delegates.md#194-delegate-compatibility)) with the delegate type D.

The first sentence seems to at least *imply* that an implicit conversion *only* exists from a method group to a compatible delegate type, but the rest of the description appears to say that an implicit conversion exists from a method group to a delegate type if a single method within the group is applicable in its normal form, without considering compatibility.

Now I know the first sentence doesn't say that implicit conversions *only* exist from method groups to compatible delegate types, but I think that's a reasonable implication. I suspect we want to change the wording of the first paragraph to remove comatibility.

**Comment by BillWagner** [comment]
See also #499

**Comment by BillWagner** [comment]
https://github.com/dotnet/csharpstandard/pull/263#issuecomment-1156724778 I think describes what needs to be addressed here, once #263 is merged.

**Comment by jskeet** [comment]
Pre-meeting evaluation: We're now rather further on than last June's comments - but I don't think that merged PR actually addressed the issue.
I don't think this is super-urgent, and I'd be happy to take a look at it myself later on. Just remove meeting-discuss for now? (And possibly re-assign.)

**Comment by jskeet** [comment]
Bill has a good idea of a potential fix - assigning to him to give it a try.

**Comment by jskeet** [comment]
Reopening as I mis-approved the PR that closed it. I think we still need to discuss this.
