### ISSUE TITLE
enum base type may be library types

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#56]
See [spec placeholder](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-6.0/enum-base-type.md) for details.

**Comment by Nigel-Ecma** [comment]
The change has opened up the base type too much. Originally the base type was *integral_type*, the C# 6 compiler decided to allow the `System.<x>` names for these (but not the online MS docs). The draft C# 6 has been changed to allow *struct_type*, which allows user defined struct types and nullable value types – much wider than intended.

While a number of the syntactic/parser productions in this area simply serve to convey semantics (e.g. *value_type* can be *enum_type* or *struct_type*, both of which cane just be *type_name*), so we may not be overly concerned, as a group they form a mutually left-recursive set which is an issue when we've switch to using ANTLR as the notation – ANTLR can't handle mutual left recursion (ANTLR 4 can handle self left recursion). Making `enum_base` dependent on `struct_type` just complicates dealing with the mutual left recursion.

This issue will hopefully be resolved by future changes to the grammar, but I'm flagging it here so this can be checked at some point.

As the changes are future unknowns the issues this is dependent on are as yet unknown but I'll tag it dependency.

**Comment by jskeet** [comment]
I've lost track of this one a bit - I thought we were going to close it (given the "resolved: by-design" label) but Nigel's comment suggests maybe we shouldn't.

**Comment by Nigel-Ecma** [comment]
To save time I'll close this; there is a PR coming which will fix the fix and the trail can be noted in that PR.

(I hope we're not seeing the early ripples of the fate of the IBM 360, fixing the fixes...)
