### ISSUE TITLE
bad display of logical and conditional OR in the table in section 11.4.2

### ISSUE THREAD

**Issue by BSeyfi** [dotnet/csharpstandard#564]
In the table in section [11.4.2](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1142-operator-precedence-and-associativity) , logical OR and conditional OR operators are not displayed properly. 
They're displayed in escaped form .
Now they are: \\|   and \\|\\|
It is expected to be: | and ||

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4836bf-72a8-e53b-0a72-5fb9c184291a
* Version Independent ID: 0d19d86e-877f-7335-7128-385ccfb21e9a
* Content: [Expressions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1142-operator-precedence-and-associativity)
* Content Source: [standard/expressions.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by RexJaeschke** [comment]
@BSeyfi I'm not seeing the problem. These look OK to me when rendered in GitHub for both V6 and V7 branches. And the V6 Word version has it right.

**Comment by BSeyfi** [comment]
@RexJaeschke 
An screenshot of my Firefox internet browser
I've also checked Chrome. Problem exists there too.

![1](https://user-images.githubusercontent.com/42473071/166103967-fd4679b9-9c5d-4652-831e-f0624e6835ef.png)

**Comment by BillWagner** [comment]
@RexJaeschke This is only an error in the v7 branch. I just opened #565 to address it.

**Comment by BSeyfi** [comment]
Thanks. Now it is OK.
