### ISSUE TITLE
9.6 Atomicity of variable references - 64-bit values

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/csharpstandard#581]
In section 9.6, the spec states:

> Reads and writes of other types, including `long`, `ulong`, `double`, and `decimal`, as well as user-defined types, need not be atomic.

I assume this part of the spec still comes from the days of 32-bit machines and runtimes.

`long`, `ulong`, and `double` are all 64-bit value types. (I don't remember what `decimal` is.)

Could these be non-atomic even on a 64-bit runtime?

**Comment by DaneSpiritGOD** [comment]
I have received.
