### ISSUE TITLE
ECMA-334:2022 not on TC49-TG2 web page

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#620]
ECMA-334 6th edition was published in June 2022 but it is not listed at <https://www.ecma-international.org/task-groups/tc49-tg2/?tab=scope>, in the table that compares Microsoft C# versions, ECMA standards, and ISO/IEC standards. Should it be added?

**Comment by KalleOlaviNiemitalo** [comment]
The similar table at <https://www.ecma-international.org/publications-and-standards/standards/ecma-334/> does include ECMA-334:2022.

**Comment by RexJaeschke** [comment]
Thanks; this has been updated as you suggested.
