### ISSUE TITLE
14.6.1: Add example for null conditional invocation expression

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#621]
14.6.1 includes:

> when recognising a method_body if both the null_conditional_invocation_expression and expression alternatives are applicable then the former shall be chosen.

11.16.1 includes the same text, and local functions will introduce it as well.

There's no motivation given for it; @gafter had an explanation around it being classified as "None" in a way which would make it invalid as an expression in some cases. (That's a very hand-wavy explanation - Neal will be able to express it better.)

We should provide motivation and an example (just informatively) in 14.6.1, and refer to it in 11.16.1 and local functions (#104).

**Comment by gafter** [comment]
There is now a PR to address this.
