### ISSUE TITLE
v7.x Q's re tuples

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#64]
In Draft PR https://github.com/ECMA-TC49-TG2/csharpstandard/pull/63, I've added almost all the edits to support the addition of tuples. Here's what's missing:

1. C# 7.1 added support for "Inferring tuple names." See the proposal https://github.com/dotnet/csharplang/blob/standard-proposals/proposals/csharp-7.1/infer-tuple-names.md. This needs to be integrated somehow, but I'm not the person to do that.

1. I've added the new construct "Deconstruction expressions" to the Expressions clause, but it needs to be "plugged into" the grammar, so it has precedence. (Also, for now, I've put this new section *after* assignment, but assuming it has precedence higher than assignment, we might want to move it earlier in the clause.)

**Comment by BillWagner** [comment]
Fixed in #664
