### ISSUE TITLE
Create workflow for our test validation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#669]
The test validation we've added should run on each PR.

We want to ensure that each PR that might change any sample code still runs.

This should follow the workflows used for the other actions.

Open question: Should it be required? (I'm not sure how far we've gotten in validating all the existing samples)

**Comment by jskeet** [comment]
All the examples that have metadata (as Example) run correctly (at least on my machine)...

**Comment by jskeet** [comment]
We shouldn't require that every example is runnable though.
