### ISSUE TITLE
Error in 9.3.3, "Default constructors", for decimal type

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#68]
[9.3.3 Default constructors](https://github.com/ECMA-TC49-TG2/csharpstandard/blob/draft-v6/standard/types.md#933-default-constructors) states

> All value types implicitly declare a public parameterless instance constructor called the ***default constructor***. The default constructor returns a zero-initialized instance known as the ***default value*** for the value type:
> -  For all *simple_type*s, the default value is the value produced by a bit pattern of all zeros:
>    - ...
>    - For `float`, the default value is `0.0f`.
>    - For `double`, the default value is `0.0d`.
>    - For `decimal`, the default value is `0.0m`.
>    - ...

The value `0.0m` is *zero with a scale of 1* when I believe it should be *zero with a scale of 0*. (The runtime certainly displays that default value as `0` rather than `0.0`.) As such, I propose the following replacement:

>    - For `decimal`, the default value is `0m` (that is, value zero with scale 0).

I suggest the parenthetic remark as well because with `decimal` literals trailing zeros are significant whereas they are not in the `0.0f` and `0.0d` cases above (from which this entry might well have been [incorrectly] cloned.

**Comment by fubar-coder** [comment]
@jskeet The PR seems to be merged already?

**Comment by jskeet** [comment]
Indeed. Not quite sure what happened there, but I'll just close it now...
