### ISSUE TITLE
Invalid example in "Using static directives"

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#689]
In [this section](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/namespaces.md#1354-using-static-directives), we have the following narrative and example:, 

A *using_static_directive* only imports members and types declared directly in the given type, not members and types declared in base classes.

> *Example*:
>
> ```csharp
> namespace N1 
> {
>     static class A 
>     {
>         public static void M(string s){}
>     }
>
>     static class B : A        // *** THE PROBLEM STARTS HERE ***
>     {
>         public static void M2(string s){}
>     }
> }
>
> namespace N2
> {
>     using static N1.B;
>
>     class C
>     {
>         void N()
>         {
>             M2("B");      // OK, calls B.M2
>             M("C");       // Error. M unknown 
>         }
>     }
> }
> ```
>
> the *using_static_directive* imports the method `M2` contained in `N1.B`, but does not import the method `M` contained in `N1.A`. Thus, the reference to `M` in the body of `C.N` results in a compile-time error because no members named `M` are in scope. Developers must add a second `using static` directive to specify that the methods in `N1.A` should also be imported.
>
> *end example*

The intent is there be only 1 compilation error, on the method call `M("C")`, as noted in the accompanying comment. However, there is another error, which prohibits the example from demonstrating its point. That error occurs on the line

 ```csharp
static class B : A
```

In [14.2.2.4.1 General](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/classes.md#142241-general), we have

> A static class declaration is subject to the following restrictions:
> 
> - ...
> - A static class shall not include a *class_base* specification ([§14.2.4](classes.md#1424-class-base-specification)) and cannot explicitly specify a base class or a list of implemented interfaces. A static class implicitly inherits from type `object`.

So, we must remove `A` as a base class. That leaves the implicit base `System.Object`. So, what member from that type can we try to access, and fail, as the example is intended to demonstrate? I tried `ReferenceEquals` among other members, but anything I put inside method `N` is inside class `C` which is also derived implicitly from `System.Object`, and *does* allow me access to that base's members.

I have not come up with a resolution.

**Comment by KalleOlaviNiemitalo** [comment]
Could resolve by making the classes A and B not static.

```C#
namespace N1 
{
    class A 
    {
        public static void M(string s){}
    }

    class B : A
    {
        public static void M2(string s){}
    }
}

namespace N2
{
    using static N1.B;

    class C
    {
        void N()
        {
            M2("B");      // OK, calls B.M2
            M("C");       // Error. M unknown 
        }
    }
}
```

[SharpLab](https://sharplab.io/#v2:CYLg1APgdghgtgUwM4AcYGMEAIByBGLAWACgBvErSrAAQCYsBBI4qrcl1q6gZhrwDYaAFiwBZABTU8ABixIAlKQC+FKiuKrKdLACEsIRprZHWPPoOojRtSTLmL1rdepKxEqDNhy0S7U7KlBfAA6HQBuEiNtAGEjP04tERxxeRMqeITWa3EAIh0c+TCEgHpirAB5AGkAGix0GAAbBqRdYOs0hIkc6IKikrKAUQAnIYB7IeCxLABXKABrKFGAdyhmTKxHNRIlIA===)

**Comment by RexJaeschke** [comment]
@KalleOlaviNiemitalo Yes, that solves it; thanks!

**Comment by KalleOlaviNiemitalo** [comment]
Do you intend to publish any corrigenda via ECMA?

(I thought examples were informative rather than normative, but [§5 Conformance](https://github.com/dotnet/csharpstandard/blob/721ef2964efeb5b4b803e856a00094dc4fe21bb7/standard/conformance.md) does not say so, and [Guidelines to Spec Writing and Formatting](https://github.com/dotnet/csharpstandard/blob/721ef2964efeb5b4b803e856a00094dc4fe21bb7/admin/guidelines-for-spec-writing-and-formatting.md) mentions "Examples and Notes **marked as such** are informative".)

**Comment by RexJaeschke** [comment]
@KalleOlaviNiemitalo Unlike ISO's Technical Corrigendum [TC], Ecma has no formal mechanism to publish errata, although any Ecma committee could make errata available informally in some public place. The C# committee has never done that. Having produced TCs  myself for other (ISO-related) standards committees, it can be a lot of work. Note that our current plan is to produce a new revision of the whole spec every 12 months. 

Yes, examples and notes are informative although §5 Conformance doesn't say so (and it probably should), but [§4 General description](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/general-description.md#4-general-description) does.

**Comment by KalleOlaviNiemitalo** [comment]
I imagine the committee could just fix the errors on the branches, on top of the tags.

- <https://github.com/dotnet/csharpstandard/compare/V5-standard...standard-v5>
- <https://github.com/dotnet/csharpstandard/compare/V6-standard...standard-v6>

I don't know whether any current sponsors would want to spend resources on that, though.

**Comment by RexJaeschke** [comment]
Up to now, once each Ecma spec has been approved by Ecma, it has been Fast-Tracked to ISO/IEC JTC 1, and adopted as an ISO spec as well. Changing anything on the Ecma site would *not* get applied to the ISO version, and we don't want the published versions to differ.

**Comment by KalleOlaviNiemitalo** [comment]
> Unlike ISO's Technical Corrigendum [TC], Ecma has no formal mechanism to publish errata

Clause 9.5 of [Ecma By-laws (June 2022)](https://www.ecma-international.org/policies/by-laws/) describes the publication of a Corrigendum "when a Standard or a Technical Report contains errors which makes it unusable as published".  Does "errata" specifically mean errors that do not have that effect?

**Comment by RexJaeschke** [comment]
@KalleOlaviNiemitalo I just found last week that Ecma _does_ have the ability to publish a Corrigendum, but this has very rarely been used. When I mentioned "errata," I was thinking about how one might make available to the public important corrections that are not in the latest adopted standard. However, maintaining an errata list _separate_ from a merged PR against the current draft that has those changes means extra work, and, frankly, we don't have the resources within TG2 for that.
