### ISSUE TITLE
run-converter.sh ERROR:gpu_init.cc(481)]

### ISSUE THREAD

**Issue by GEricson** [dotnet/csharpstandard#699]
Running run-converter.sh from command prompt on Windows 10.

```
[main 2023-01-05T18:56:03.981Z] update#setState idle
[main 2023-01-05T18:56:06.074Z] UtilityProcess<1>: Creating new...
[main 2023-01-05T18:56:06.202Z] UtilityProcess<1>: received spawn event.
[main 2023-01-05T18:56:33.986Z] update#setState checking for updates
[main 2023-01-05T18:56:34.089Z] update#setState idle
[24828:0105/135802.331:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
[main 2023-01-05T20:26:34.256Z] update#setState checking for updates
[main 2023-01-05T20:26:34.714Z] update#setState idle
```
The program is running for hours...

**Comment by jskeet** [comment]
That doesn't look like any output from run-converter that I've ever seen. I suspect it's either an issue in the version of bash you're using, or your dotnet installation.

If you look at the shell script, you can run each individual command there and work out which part is hanging.

**Comment by jskeet** [comment]
Closing as we haven't had any more feedback.
