### ISSUE TITLE
Identity conversion and "Considered equivalent"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#730]
See https://github.com/dotnet/csharpstandard/pull/664/files#r1093246493

We use the same language that "dynamic and object are considered equivalent" in the section on identity conversions.

That is somewhat troubling because they aren't "equivalent". We should search for better wording.

---
[Associated WorkItem - 177627](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177627)

**Comment by jskeet** [comment]
Note from @gafter: the same applies to "the same type"almost everywhere it is used. We actually mean types for which an identity conversion exists.

**Comment by BillWagner** [comment]
Proposal:

1. [8.7](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#87-the-dynamic-type), introduce the term *"Interchangeable"* to define the relationship between `object` and `dynamic`. This is the third mention of `dynamic` in the spec. The first is in 7.6, in Basic concepts/Signatures and Overloading where it says that overloads can't differ only in `dynamic` / `object`. The second is in 8.2.4, which introduces the `dynamic` type, and has a forward reference to 8.7.
2. In [10.2.2](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#1022-identity-conversion) Identity conversions, reinforce the term "Interchangeable" and refer back to the definition in 8.7.
3. In other sections, search for "the same type" (34 occurrences), and "considered equivalent" (2 occurrences) and replace those with "`dynamic` and `object` are interchangeable". (Do we need an xref back to 8.7 and the definition in all locations?)

**Comment by jskeet** [comment]
Suggestion of "runtime interchangeable" (with or without hyphen) to make it clear they're not *globally* interchangeable. And we'll need to look at tuples too. We can make the term effectively a shorthand way of saying "there is an identity conversion between these types" - so possibly define it there.

**Comment by jskeet** [comment]
Bill will create a proposal PR for the next meeting (possibly non-exhaustive).

**Comment by BillWagner** [comment]
Changes requested in the last ECMA meeting. Updating for another review.
