### ISSUE TITLE
Missing query expression translation for `select into`

### ISSUE THREAD

**Issue by svick** [dotnet/csharpstandard#741]
[Section 11.18.3.2 of the spec](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#111832-select-and-group--by-clauses-with-continuations) is called "select and group … by clauses with continuations", but it only describes the translation of `group by into`, not `select into`. And I didn't find the translation of `select into` described anywhere else either, so this seems to be an omission in the standard.

**Comment by jskeet** [comment]
Thanks, this does look like an omission - we'll discuss it in our meeting next week.

**Comment by jskeet** [comment]
This is covered by the MS C# 5 spec, but broken in the ECMA C# 5 standard.

The version that covers it is just terse:

> A query expression with a continuation
>     `from … into x …`
> is translated into
>     `from x in ( from … ) …`
>
>The translations in the following sections assume that queries have no into continuations.

**Comment by BillWagner** [comment]
The final MS Spec C# 6 text is [here](https://github.com/dotnet/csharplang/blob/ms-spec-text/spec/expressions.md#select-and-groupby-clauses-with-continuations). It mirrors the MS C# 5 spec text.

**Comment by jskeet** [comment]
Eric has volunteered to take this on. We would like to fix it sooner rather than later as a point of pride :)

**Comment by ericlippert** [comment]
Thanks @svick  for catching this one; I've changed the title of the section and updated the text to more clearly describe the translation, in the v7 draft branch.
