### ISSUE TITLE
Write something about spec compliance and Roslyn

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#744]
(Known non-compliance etc.)

**Comment by gafter** [comment]
Please see all of the documents in https://github.com/dotnet/roslyn/tree/main/docs/compilers/CSharp . Some of them are about compiler/spec deviations. Also the Microsoft-internal notebook mentioned by @333fred .

**Comment by BillWagner** [comment]
closing as this should be done in the roslyn repo, not here.

Closed in favor of dotnet/roslyn#70043 to make sure we don't lose anything.
