### ISSUE TITLE
8.5.5 Accessibility constraints for types in generic constraints

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#75]
The list of constraints in 9.5.5 doesn't mention generic constraints, so doesn't (as far as I can tell) forbid something like this:

```
public class Foo<T> where T : Bar {}
internal class Bar {}
```

All three compilers we're interested in _do_ prohibit this, so the spec should mention it too.

**Comment by jskeet** [comment]
Assigned to @ericlippert as a "starter issue" :)

**Comment by ericlippert** [comment]
I do not know what "complicated case involving nested types" Vladimir had in mind, but consider this simple case involving nested types:

    internal class B {}
    internal class X {
      public class C<T> where T : B {}
    }
    
This is legal; though C<T> is declared public, it is accessible only to code which can see X, and therefore B is not more restricted in its accessibility than C<T> is.

**Comment by ericlippert** [comment]
Section 8.5.5 begins with a formal definition ("A type T is said to be at least as accessible as..."), and then uses this definition in a list of requirements ("The direct base class of a class type shall be at least as accessible as the class type itself.")  None of these requirements call out cases involving nested types; rather, all cases involving nested types are described in 8.5.3, which defines accessibility domain.

Thus Jon's wording seems reasonable to me, but I would make some minor modifications. Jon proposes:

> A class or interface type used within a type parameter constraint shall be at least as accessible as the member declaration which includes the constraint.

First: what is "used within" intended to convey here? We say "The direct base class..." and not "*A type used within* the direct base class..."  

If "used within" is intended to cover situations such as `Foo<T> where T : IList<Bar>`, that is already covered by section 8.5.3, which notes that the accessibility domain of `IList<Bar>` is the intersection of the accessibility domains of `IList` and `Bar`.

Second: the use of "declaration" seems to be redundant here; again, we say "... the class type" and not "the class type declaration". But in other parts of the spec we refer to a type parameter constraint as "declared", not "included".

I therefore propose:

> An interface or class type constraint on a type parameter shall be at least as accessible as the member which declares the constraint.

**Comment by jskeet** [comment]
Definitely happy with "declares" rather than "includes". I was slightly wary of removing the separation between a class/interface and a class/interface type constraint, but it does seem to be consistent with https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/classes.md#1525-type-parameter-constraints... and I think it's clear what it means.
