### ISSUE TITLE
SZARRAY encoding in XML documentation ID string

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#772]
**Describe the bug**

§D.4.2 _ID string format_ specifies that, when an array type is encoded in the ID string, the lower bound and size of each dimension is also encoded if known:

<https://github.com/dotnet/csharpstandard/blob/721ef2964efeb5b4b803e856a00094dc4fe21bb7/standard/documentation-comments.md?plain=1#L642>

However, one-dimensional zero-bound unspecified-size arrays (ELEMENT_TYPE_SZARRAY in ECMA-335) are actually encoded with just `[]` rather than `[0:]`.

Also, multidimensional arrays appear to have `0:` for each dimension. According to §16.1, C# array types have a lower bound of zero in every dimension. It might be worth adding a note about this to §D.4.2, especially because the System.Type and System.Reflection.ParameterInfo APIs do not provide methods for querying the bounds of an array type, although System.Array has methods for querying the bounds of an array instance.

<https://github.com/dotnet/csharpstandard/blob/721ef2964efeb5b4b803e856a00094dc4fe21bb7/standard/arrays.md?plain=1#L7>

(I suppose it might be possible to define a non-zero-bound array parameter in a different programming language and reference that with the C# XML documentation comments `cref` attribute, in which case the C# compiler might generate an ID string with the non-zero-bound syntax.)

**Example**

ArrayDoc.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>6.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
```

ArrayDoc.cs:

```csharp
public abstract class ArrayDoc
{
    /// <summary>Some method</summary>
    protected abstract void M(int[] a, int[,] b);
}
```

Generated ArrayDoc.xml:

```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ArrayDoc</name>
    </assembly>
    <members>
        <member name="M:ArrayDoc.M(System.Int32[],System.Int32[0:,0:])">
            <summary>Some method</summary>
        </member>
    </members>
</doc>
```

Note the ID string is not ```M:ArrayDoc.M(System.Int32[0:],System.Int32[0:,0:])```.

**Expected behavior**

Declare that a one-dimensional, zero-bound array type is encoded in the ID string as `[]` rather than `[0:]`.

Perhaps add a note saying that array types defined in C# always have a lower bound of zero, with a cross reference to §16.1.

**Additional context**

I vaguely recall that a one-dimensional, unknown-lower-bound array type might be encoded as `[*]`, but I don't remember where I saw that. It's not ECMA-335 §II.14.2, which uses `[...]` instead.

---
[Associated WorkItem - 178981](https://dev.azure.com/msft-skilling/Content/_workitems/edit/178981)

**Comment by svick** [comment]
> I vaguely recall that a one-dimensional, unknown-lower-bound array type might be encoded as [*], but I don't remember where I saw that.

[It's `Type.ToString()` that does that:](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AH2ATwA4FMD2AzACgEspgBKAOgFkBDAaywEEwwa0AVTLAy9nAZWBgSAcx4UAIhAC2GHgG4AsACh02fMVKVaDZqw5cCARl4Cho8VNkKVQA===)

```c#
typeof(int).MakeArrayType().ToString() // SZARRAY, returns "System.Int32[]"
typeof(int).MakeArrayType(1).ToString() // one-dimensional, zero-bound MDARRAY, returns "System.Int32[*]"
```
