### ISSUE TITLE
Address outstanding comments on patterns

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#774]
We merged #757 with several comments still open, in order to get the first draft to ECMA members.

This issue is basically a reminder that we should still go through them. Neal, feel free to just resolve any that have been addressed, or @ people for more details if they're insufficient. I'd expect that a single PR could address a bunch of the niggles that were left as comments.

**Comment by jskeet** [comment]
@gafter: Are you able to look at these during August at all?

**Comment by gafter** [comment]
Adressing this now.  I will resolve or comment on each open comment on that PR.
