### ISSUE TITLE
Possible issue with constructor parameters

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#782]
See https://github.com/dotnet/csharpstandard/pull/219/files#r1171850693

The wording doesn't describe if there is any distinction between optional and required parameters in a constructor and if that distinction is considered part of the constructor signature.

**Comment by jskeet** [comment]
Marking as a bug because I *believe* it is, but I won't put time into this until after we've shipped C# 7, as I don't believe we're in a worse position than we were before.
