### ISSUE TITLE
Possible typo in type inference

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#787]
From https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#12632-the-first-phase, after an introduction which sets the scene with:

```csharp
Tₑ M<X₁...Xᵥ>(T₁ p₁ ... Tₓ pₓ)
```

we have this text:

> For each of the method arguments `Eᵢ`:
> 
> - If `Eᵢ` is an anonymous function, an *explicit parameter type inference* ([§12.6.3.8](expressions.md#12638-explicit-parameter-type-inferences)) is made *from* `Eᵢ` *to* `Tᵢ`
> - Otherwise, if `Eᵢ` has a type `U` and `xᵢ` is a value parameter ([§15.6.2.2](classes.md#15622-value-parameters)) then a *lower-bound inference* ([§12.6.3.10](expressions.md#126310-lower-bound-inferences)) is made *from* `U` *to* `Tᵢ`.
 >- Otherwise, if `Eᵢ` has a type `U` and `xᵢ` is a reference ([§15.6.2.3](classes.md#15623-reference-parameters)) or output ([§15.6.2.4](classes.md#15624-output-parameters)) parameter then an *exact inference* ([§12.6.3.9](expressions.md#12639-exact-inferences)) is made *from* `U` *to* `Tᵢ`.
> - Otherwise, no inference is made for this argument.

Should the `xᵢ` in the second and third bullets be `pᵢ`?

I'll probably just create a PR for this, but it was easier to file an issue to start with...

**Comment by Nigel-Ecma** [comment]
Well a parameter has the grammar:

>```
>attributes? parameter_modifier? type identifier default_argument?
>```

Matching `Tₑ M<X₁...Xᵥ>(T₁ p₁ ... Tₓ pₓ)` to this the `Tᵢ` are the *type* and `pᵢ` the *identifier*. Neither of these determine whether the parameter is value or reference parameter, that is down to the *parameter_modifier*. So it seems the writer is using `xᵢ` as the whole parameter spec but does not define it as such, so the `xᵢ` are neither `pᵢ` or `Tᵢ`…

We could try:

> - Otherwise, if `Eᵢ` has a type `U` and the i<sup>th</sup> parameter is a value parameter ([§15.6.2.2](classes.md#15622-value-parameters)) then a *lower-bound inference* ([§12.6.3.10](expressions.md#126310-lower-bound-inferences)) is made *from* `U` *to* `Tᵢ`.
 >- Otherwise, if `Eᵢ` has a type `U` and the i<sup>th</sup> parameter is a reference ([§15.6.2.3](classes.md#15623-reference-parameters)) or output ([§15.6.2.4](classes.md#15624-output-parameters)) parameter then an *exact inference* ([§12.6.3.9](expressions.md#12639-exact-inferences)) is made *from* `U` *to* `Tᵢ`.

Which skirts introducing another letter and requires HTML &lt;sup&gt; tags in the source :-)

**Comment by jskeet** [comment]
Fixed in #975
