### ISSUE TITLE
Move volatile field text to unsafe chapter

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#800]
see https://github.com/dotnet/csharpstandard/pull/795/files#r1217082636

There is an additional issue for other text that could also move to the unsafe text.

**Comment by KalleOlaviNiemitalo** [comment]
What's the motivation: do you intend that implementations that do not allow `unsafe` (such as Roslyn without the unsafe-code option) would be required to emit a diagnostic whenever `volatile` is used?

**Comment by BillWagner** [comment]
Adding the meeting discuss label. 

This is based on @gafter 's comment referenced above to move text into the *unsafe* chapter. The text in question is that a warning is issued when a `volatile` field is passed as an argument to an `in`, `out`, or `ref` parameter. None of those features require unsafe. 

So, should this requirement move?

**Comment by jskeet** [comment]
Example of the warning:

```csharp
class Test
{
    volatile static int x;

    static void Main()
    {
        M(ref x);
    }

    static void M(ref int y)
    {
    }
}
```

Warning: warning CS0420: 'Test.x': a reference to a volatile field will not be treated as volatile

**Comment by jskeet** [comment]
We've decided to close this without action as the warning and feature have nothing to do with unsafe code.
