### ISSUE TITLE
`in` parameters, `dynamic` parameters and arguments

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#802]
See https://github.com/dotnet/csharpstandard/pull/795/files#r1215631063

The interaction between `dynamic` (as an argument, or a parameter) and `in` parameter or `in argument` is not specified correctly.

There are several cases to cover:

- `in dynamic` as parameter
  - `in dynamic` as argument
  - `dynamic` as argument
  - other reference type as argument
  - other value type as argument
- other type as parameter
  - `in dynamic` as argument
  - `dynamic` as argument.
 

---
[Associated WorkItem - 98103](https://dev.azure.com/msft-skilling/Content/_workitems/edit/98103)

**Comment by BillWagner** [comment]
The following program answers most of the questions for the single parameter cases:

```csharp
using System;

internal class Program
{
    private static void Main(string[] args)
    {
        dynamic d = 5;
        object o = new object();
        int j = 42;

        var c = new C();

        c.M(in d);
        c.M(d); // Runtime binder exception (best overload has invalid arguments)
        c.M(in o);
        c.M(o);
        // c.M(in j); // CS1503: Cannot convert from 'in int' to 'in dynamic'
        c.M(j);

        c.M2(in j);
        c.M2(j);
        // c.M2(in d); // CS1503: Cannot convert from 'in dynamic' to 'in int'
        c.M2(d); // Runtime binder exception (best overload has invalid arguments)
        // c.M2(in o); // CS1503: Cannot convert from 'in object' to 'in int'
        // c.M2(o); // CS1503: Cannot convert from 'object' to 'in int'

        c.M3(in d);
        c.M3(d); // Runtime binder exception (best overload has invalid arguments)
        c.M3(in o);
        c.M3(o);
        // c.M3(in j); // CS1503: Cannot convert from 'in int' to 'in object'
        c.M3(j);
    }
}

public class C
{
    public void M(in dynamic p) => Console.WriteLine(p);
    public void M2(in int p) => Console.WriteLine(p);
    public void M3(in object p) => Console.WriteLine(p);
}
```

**Comment by jaredpar** [comment]
> The interaction between dynamic (as an argument, or a parameter) and in parameter or in argument is not specified correctly.

In the case `in` is specified it will have behavior similar to `ref`, outside that it is not supported.

**Comment by BillWagner** [comment]
> In the case `in` is specified it will have behavior similar to `ref`, outside that it is not supported.

@jaredpar 

For the spec, should we use the language "the behavior is undefined"? So, from the examples above, anywhere the method is `void M(in dynamic d)`, and the argument doesn't have the `in` modifier, the result is undefined?

**Comment by BillWagner** [comment]
> For the spec, should we use the language "the behavior is undefined"?

Answered offline: Yes, this is the best solution.
