### ISSUE TITLE
identity conversion merging rules for tuples, dynamic / object and `? :`

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#803]
See https://github.com/dotnet/csharpstandard/pull/795/files#r1217424913

This is larger in scope. We don't currently describe the merging rules for identity conversions where tuples with named members, or `dynamic` and `object` are used in `?:` or as tuple members.

---
[Associated WorkItem - 98104](https://dev.azure.com/msft-skilling/Content/_workitems/edit/98104)

**Comment by jskeet** [comment]
@BillWagner: Any progress on this?

**Comment by BillWagner** [comment]
@jskeet Merging #821 will close this.
