### ISSUE TITLE
C# 7.3 method_body etc. grammar does not allow `=> ref`

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#825]
**Describe the bug**

In C# 7.3, a method/property/accessor/indexer body <code>=> ref <var>variable_reference</var>;</code> should be allowed and mean the same as <code>{ return ref <var>variable_reference</var>; }</code>.  Roslyn allows this, but the grammar in the C# 7 draft doesn't.

This issue concerns multiple clauses, listed under "Expected behavior" below.

**Example**

The following should be allowed, but `=> ref field` does not match the syntactic grammar.

```csharp
class C {
    int field;
    ref int ShortProperty => ref field;
    ref int LongProperty { get => ref field; }
    ref int this[int index] => ref field;
    ref int Method() => ref field;
    void Outer() {
        ref int Inner() => ref field;
    }
}
```

**Expected behavior**

In §15.7.1 (Classes / Properties / General), _property_body_  should allow `=>` `ref` _variable_reference_ `;`.

In §15.7.3 (Classes / Properties / Accessors), _accessor_body_ should allow `=>` `ref` _variable_reference_ `;`.

In §15.9 (Classes / Indexers), _indexer_body_ should allow `=>` `ref` _variable_reference_ `;`.

In §15.6.1 (Classes / Methods / General), _method_body_  should allow `=>` `ref` _variable_reference_ `;`.

In §13.6.4 (Statements / Declaration statements / Local function declarations), _local_function_body_ should allow `=>` `ref` _variable_reference_ `;`.

The standard should specify what the `=>` `ref` syntax means, perhaps by reference to §13.10.5 (Statements / Jump statements / The return statement), which specifies the meaning of `return` `ref`.

**Additional context**

In §12.19.1 (Expressions / Anonymous function expressions / General), _anonymous_function_body_ already allows `ref` _variable_reference_.  However, I haven't found anything that specifies what `ref` means in this context.

In §15.10.1 (Classes / Operators / General), _operator_body_ does not allow `=>` `ref` _variable_reference_ `;` but this is OK as operators cannot return by reference; _operator_declarator_ does not allow `ref` either.

In §15.11.1 (Classes / Instance constructors / General), _constructor_body_ does not allow `=>` `ref` _variable_reference_ `;` but this is OK as instance constructors cannot return values either.

In §15.12 (Classes / Static constructors), _static_constructor_body_ does not allow `=>` `ref` _variable_reference_ `;` but this is OK as static constructors cannot return values either.

In §15.13 (Classes / Finalizers), _finalizer_body_  does not allow `=>` `ref` _variable_reference_ `;` but this is OK as finalizers cannot return values either.

_Elaborated from <https://github.com/dotnet/csharpstandard/issues/213#issuecomment-852688736>_

**Comment by jskeet** [comment]
@Nigel-Ecma: If you've got bandwidth to look at this, that would be great - if not, let me know and I'll see if @gafter can.

**Comment by KalleOlaviNiemitalo** [comment]
The specification of this feature should be at <https://github.com/dotnet/csharplang/blob/cd336064a26a43c31c1164ef7cd3f5feb4420d20/proposals/csharp-7.0/expression-bodied-everything.md> or <https://github.com/dotnet/csharplang/blob/cd336064a26a43c31c1164ef7cd3f5feb4420d20/proposals/csharp-7.0/ref-locals-returns.md> but both are only placeholders.

**Comment by Nigel-Ecma** [comment]
Covered by PR #837
