### ISSUE TITLE
C# 7.3 interface_method_declaration etc. grammar does not allow return by reference

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#826]
**Describe the bug**
In C# 7.3, a method, property, or indexer as a member of an interface should be able to return by (readonly) reference, but the syntactic grammar does not allow this.

§18.4.2, §18.4.3, §18.4.5.

**Example**

The following should be allowed, but `ref` does not match the syntactic grammar.

```csharp
interface I {
    ref int Method();
    ref int Property { get; }
    ref int this[int index] { get; }
}
```

**Expected behavior**

In §18.4.2, _interface_method_declaration_  should allow `ref` or `ref` `readonly` before _return_type_.

In §18.4.3, _interface_property_declaration_  should allow `ref` or `ref` `readonly` before _type_.  It is not necessary to explicitly forbid a `set` accessor on such a property, because the text already references §15.7.3, which states: "A ref-returning property shall not have a `set` accessor."

In §18.4.5, _interface_indexer_declaration_ should allow `ref` or `ref` `readonly` before _type_.  It is not necessary to explicitly forbid a `set` accessor on such an indexer, because the text already references §15.9, which states: "Aside from these differences, all rules defined in §15.7.3 and §15.7.4 apply to indexer accessors as well as to property accessors."

**Additional context**

In §18.4.4, _interface_event_declaration_  does not allow `ref`, but that is OK, because the _type_ is not the return type of any accessor of the event.

Operators cannot be members of interfaces, and they do not allow `ref` in classes and structs either.

**Comment by jskeet** [comment]
@Nigel-Ecma: With your grammarian hat on, does this look like it's easy enough to fix?

**Comment by Nigel-Ecma** [comment]
This will be covered by PR #837 along with issue #825
