### ISSUE TITLE
C# 7.3 §15.10.1 operator with `in` parameter modifier

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#835]
**Describe the bug**

C# 7 draft §15.10.1 (Classes / Operators / General) states:

> The parameter(s) of an operator shall have no modifiers.

However, the `in` parameter modifier should be allowed.  The C# compiler in .NET SDK 7.0.107 allows it when LangVersion is 7.3.

**Example**

This should be allowed:

```csharp
public struct S {
    public static S operator +(in S a, in S b) {
        return default(S);
    }
}
```

**Expected behavior**

The parameter(s) of an operator shall have no modifiers other than `in`.

(The `this`, `out`, `ref`, and `params` modifiers remain disallowed.)

**Additional context**

None.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/csharplang/blob/cd336064a26a43c31c1164ef7cd3f5feb4420d20/proposals/csharp-7.2/readonly-ref.md> says `in` is allowed in parameters of operators:

> - `in` parameters are allowed anywhere where ordinary byval parameters are allowed. This includes indexers, operators (including conversions), delegates, lambdas, local functions.
>
>> ```csharp
>>  (in int x) => x                                                     // lambda expression  
>>  TValue this[in TKey index];                                         // indexer
>>  public static Vector3 operator +(in Vector3 x, in Vector3 y) => ... // operator
>>  ```

**Comment by jskeet** [comment]
Created #842 which would fix this - it *seems* okay to me, even though a caller can never explicitly specify `in` on the argument. I may be missing something though...

**Comment by Nigel-Ecma** [comment]
@jskeet – not being able to specify `in` is fine as by-val arguments can be passed as `in` parameters. So this does allow operators to have readonly references passed to avoid copying large values.

**Comment by jskeet** [comment]
@Nigel-Ecma: Yup, sorry, I should have made it clear that it's just a bit of an oddity.
