### ISSUE TITLE
Checks around `ref` & ` ref readonly` required.

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#836]
_Adding this as an issue so it’s checked off before v7._

Recent issues have brought to light that the introduction of `ref` and `ref readonly` into v7 is unfortunately incomplete and where they are allowed and the rules governing them need to be checked to ensure v7 makes sense in this area.

Recent issues, and PRs if applicable, concerning `ref` & `ref readonly`:

- #825, missing expression bodied functions variants (assigned, PR in progress)
- #826, support in interfaces (assigned, not yet in progress)
- #828, initializers – addressed by PR #831 (approved, pending merge)
- #835, `in` parameters for operators (self assigned, not yet in progress)

Issues not covered by PRs:

- Rules over assigning to `ref` & `ref readonly` variables should be checked for completeness (#828 suggests that some source material may have been sourced from earlier feature proposals and may not reflect the final intended semantics). 
- Similarly rules for combining `ref` and `ref readonly`, e.g. when a selection expression has `ref` & `ref readonly` choices, need to be checked.

`ref`, a little word with a big impact!

The above list may not be exhaustive, please add to it if needed!

Of the existing PRs only one is “in progress” right now, next other two are in my queue – feel free to dive in and take an reassign, but maybe consider checking the rules for validity as that is not covered by any PR (and of course may produce none!)

**Comment by Nigel-Ecma** [comment]
Issue #894 has highlighted some more issues not mentioned above regarding read-only, e.g. passing a variable as a ref parameter does not specify that the variable cannot be read-only (note `in` is similar to `ref readonly`)

**Comment by jskeet** [comment]
Meeting 2023-09-06: Closing in favour of the specific examples in #894; there may well still be some things we've missed, but ultimately that will always be the case.
