### ISSUE TITLE
Unsafe code diagnostics before C# 11

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#841]
<https://github.com/dotnet/csharplang/issues/6476> is a feature proposal for downgrading some errors to warnings in unsafe code.  For example, a program can declare a pointer to a type that is not an *unmanaged type*; that will result in a warning rather than an error, and the warning can be disabled.  The feature was approved for C# 11.  However, Roslyn implements it in lower versions of C# too, and this is by design according to <https://github.com/dotnet/roslyn/issues/68958>.  I wonder if this should affect the ongoing standardisation of C# 7.3.

AFAICT, the relevant requirement is in 5 Conformance:

> A conforming implementation of C# shall produce at least one diagnostic message if the source program violates any rule of syntax, or any negative requirement (defined as a “shall” or “shall not” or “error” or “warning” requirement), unless that requirement is marked with the words “no diagnostic is required”.

and 3 Terms and definitions:

> - **diagnostic message**
>   - message belonging to an implementation-defined subset of the implementation’s output messages

and again 5 Conformance:

> A conforming implementation of C# shall be accompanied by a document that defines all implementation-defined characteristics, and all extensions.

so, if the document defines the warning as a diagnostic, then this change in the compiler does not prevent it from being a conforming implementation.  Can someone verify that this is correct?

**Comment by Nigel-Ecma** [comment]
This change does not effect the specification of C# 7.3, this is a post 7.3 compiler choosing to alter how it handles this.

So my 0.02c worth is this does not effect the 7.3 standardisation.

---

Note that the compiler’s `LangVersion`, emphasis added:

> Causes the compiler to accept only _**syntax**_ that is included in the chosen C# language specification. ([source](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#langversion))

So using `LangVersion` to test semantics probably doesn't do what one might expect…

**Comment by KalleOlaviNiemitalo** [comment]
LangVersion does affect overload resolution, even though the syntax is the same.
