### ISSUE TITLE
C# 7.x 15.15.1 standard library task types

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#844]
**Describe the bug**

In the C# 7 draft, 15.15.1 says

> (The Standard library types `System.Threading.Tasks.Task<T>` and types constructed from `System.Threading.Tasks.Task` are task types.)

However, there cannot be any types constructed from `System.Threading.Tasks.Task`, because it is not a generic type.

**Example**

None

**Expected behavior**

> (The Standard library type `System.Threading.Tasks.Task` and types constructed from `System.Threading.Tasks.Task<T>` are task types.)

**Additional context**

Could also mention ValueTask and ValueTask\<T\>, which are listed in C.3 (Standard Library Types not defined in ISO/IEC 23271).

C.3 is inconsistent on whether the type parameter of these is named `T` or `TResult`.  This name is not used when referencing the type in C#, but it is stored in the ECMA-335 GenericParam table and may be readable by reflection.

**Comment by jskeet** [comment]
Hmm... it's interesting that we mention `ValueTask` at all. The only references are in basic concepts (where we say it doesn't count for a return type in async entry points) and in the standard library. I think I'll leave that inconsistency for now, but fix the generic issue and make it `Task<TResult>` everywhere.

**Comment by KalleOlaviNiemitalo** [comment]
ValueTask and ValueTask\<TResult\> will be needed in C# 8 async streams <https://github.com/dotnet/csharpstandard/pull/606>: `IAsyncDisposable` has a method `ValueTask DisposeAsync();`, and `IAsyncEnumerator<out T>` has a method `ValueTask<bool> MoveNextAsync();`.  I don't think C# 7 requiring ValueTask and ValueTask\<TResult\> would be too much of a burden to implementors.
