### ISSUE TITLE
C# 7.x notes without "end note"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#853]
**Describe the bug**

In the C# 7.x draft, the following single-line notes start with "*Note:*" but do not end with "*end note*".

§9.4.4.33 (Rules for variables in local functions):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/variables.md?plain=1#L926>

§9.7.2.6 (Ref safe contexts / Values):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/variables.md?plain=1#L1217>

§12.6.1 (Function members / General):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/expressions.md?plain=1#L425>

§12.8.1 (Primary expressions / General):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/expressions.md?plain=1#L1297>

§12.19.1 (Anonymous function expressions / General):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/expressions.md?plain=1#L4767>
* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/expressions.md?plain=1#L4827>
* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/expressions.md?plain=1#L4829>

§15.6.1 (Methods / General):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/classes.md?plain=1#L1956>

§15.6.2.1 (Method parameters / General):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/classes.md?plain=1#L2088>

§15.6.2.3 (Method parameters / Input parameters):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/classes.md?plain=1#L2102>

§15.6.2.4 (Method parameters / Reference parameters):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/classes.md?plain=1#L2118>

§22.3 (Attribute specification):

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/attributes.md?plain=1#L242>

**Example**

None.

**Expected behavior**

End each note with "*end note*".

**Additional context**

According to §4, "*end note*" should always be included.

The draft mostly uses `*Note*:`, but there are nine occurrences of `*Note:*`.

Most notes are indented with `> `,  but four notes in classes.md are not.  I listed two of them above, and the other two are:

* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/classes.md?plain=1#L2248>
* <https://github.com/dotnet/csharpstandard/blob/15fc576af042c775e37d829506f98e36eaac831f/standard/classes.md?plain=1#L3122>

**Comment by jskeet** [comment]
Closing as I believe #862 fixes all of these.
