### ISSUE TITLE
C# 7.x §15.15.1 meaning of "returns a value" in async function

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#857]
**Describe the bug**

In the C# 7.x draft, the phrase "returns a value" is used in §15.6.1 (Methods / General) and §15.15.1 (Async functions / General), but not with the same meaning.

In §15.6.1:

> If `ref` is present, the method is ***returns-by-ref***; otherwise, if *return_type* is `void`, the method is ***returns-no-value***; otherwise, the method is ***returns-by-value***.
>
> The *return_type* of a method declaration specifies the type of the result, if any, returned by the method. A returns-no-value method does not return a value. A returns-by-ref method returns a *variable_reference* ([§9.5](variables.md#95-variable-references)), that is optionally read-only. A returns-by-value method returns a value. If the declaration includes the `partial` modifier, then *return_type* shall be `void` ([§15.6.9](classes.md#1569-partial-methods)). If the declaration includes the `async` modifier then *return_type* shall be `void` or the method returns-by-value and the return type is a *task type* ([§15.15.1](classes.md#15151-general)).

i.e. if the *return_type* of an async method is a *task type*, then it is a returns-by-value method and thus "returns a value".

In §15.15.1:

> The *return_type* of an async method shall be either `void` or a ***task type***. For an async method that returns a value, a task type shall be generic. For an async method that does not return a value, a task type shall not be generic.

**Example**

The following should be allowed, but is C.M() a method that "returns a value"?

```csharp
using System.Threading.Tasks;

class C {
    async Task M() {}
}
```

According to §15.6.1, this method is *returns-by-value*, and thus "returns a value".

However, if this is "an async method that returns a value", then §15.15.1 requires that "a task type shall be generic", which System.Threading.Tasks.Task is not.

**Expected behavior**

In §15.15.1, use some other phrase than "returns a value".

**Additional context**

None.

---
[Associated WorkItem - 187393](https://dev.azure.com/msft-skilling/Content/_workitems/edit/187393)

**Comment by KalleOlaviNiemitalo** [comment]
Could perhaps say "has an *effective return type* (15.6.11) other than `void`", but I did not check whether this would result in a circular definition.

**Comment by jskeet** [comment]
Again, punting - and this one has probably been broken since C# 5. (I suspect the eventual fix will be a matter of just a few words, but choosing those words will take time...)

**Comment by KalleOlaviNiemitalo** [comment]
AFAICT, C# 5 does not have this error.  ECMA-334 5th edition uses the wording "return a value" or "returns a value" only in the following:

- §11.7.1 (Anonymous function conversions / General):
  > \[*Example*: The examples that follow use a generic delegate type `Func<A,R>` that represents a function that takes an argument of type `A` and returns a value of type `R`:
- §12.8.8.4 (Run-time evaluation of await expressions):
  > Either immediately after (if <code>*b*</code> was `true`), or upon later invocation of the resumption delegate (if <code>*b*</code> was `false`), the expression <code>(*a*).GetResult()</code> is evaluated. If it returns a value, that value is the result of the *await-expression*. Otherwise, the result is nothing.
- §15.6.1 (Methods / General):
  > The *return-type* is `void` if the method does not return a value.
- §15.7.3 (Properties / Accessors):
  > Properties often follow the pattern shown above: The `get` accessor simply returns a value stored in a private field, and the `set` accessor modifies that private field and then performs any additional actions required to update fully the state of the object.
- §23.3 (Pointer types):
  > A method can return a value of some type, and that type can be a pointer.

The sentences above do not talk about an `async` function returning a value or not.

ECMA-334 5th edition §15.15.2 (Evaluation of a task-returning async function) has:

> If the function body terminates as the result of reaching a return statement or the end of the body, any result value is recorded in the return task, which is put into a *succeeded* state.

which says "result value" rather than "return value", so this is all consistent.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/csharpstandard/pull/1027> did not fully fix this; the text still has "an async method that does not return a value".
