### ISSUE TITLE
C# 7.x §C.3 AsyncMethodBuilderAttribute has AttributeTargets.Method

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#858]
**Describe the bug**

In the C# 7.x draft, §C.3 (Standard Library Types not defined in ISO/IEC 23271), AsyncMethodBuilderAttribute has `AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface | AttributeTargets.Delegate | AttributeTargets.Enum | AttributeTargets.Method`.  Of these, AttributeTargets.Method is not needed for C# 7.3 and instead corresponds to a C# 10 feature.

**Example**

This should not be allowed in a C# 7.3 implementation without extensions.

```csharp
using System.Runtime.CompilerServices;

public class C {
    [AsyncMethodBuilder(typeof(C))]
    void M() {}
}
```

**Expected behavior**

In §C.3, remove AttributeTargets.Method from AsyncMethodBuilderAttribute.

**Additional context**

The C# 7.0 [Async Task Types in C#](https://github.com/dotnet/csharplang/blob/05ed9dcfba84a038e02301a9b267516edfe14159/proposals/csharp-7.0/task-types.md) proposal does not mention AttributeTargets.

<https://github.com/dotnet/runtime/pull/50116> added AttributeTargets.Method to AsyncMethodBuilderAttribute, for the C# 10 [AsyncMethodBuilder override](https://github.com/dotnet/csharplang/blob/05ed9dcfba84a038e02301a9b267516edfe14159/proposals/csharp-10.0/async-method-builders.md) proposal <https://github.com/dotnet/csharplang/issues/1407>.

**Comment by jskeet** [comment]
Closed by #875.
