### ISSUE TITLE
C# 7.x §9.7.2 has both text and subsections

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#860]
**Describe the bug**

In the C# 7.x draft, §9.7.2 (Ref safe contexts) contains text followed by subsections §9.7.2.1 to §9.7.2.8.

**Example**

None.

**Expected behavior**

As stated in `admin/guidelines-for-spec-writing-and-formatting.md`:

> A section should contain either subsections or text, but never both.

**Additional context**

None.

**Comment by BillWagner** [comment]
Fixed in #864
