### ISSUE TITLE
C# 7.x §B.3 does not mention implementation-defined limit of §6.5.8 #line directive

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#861]
**Describe the bug**

In the C# 7.x draft, §B.3 (Implementation-defined behavior) does not list this one from §6.5.8 (Line directives):

> The maximum value allowed for `Decimal_Digit+` is implementation-defined.

**Example**

None.

**Expected behavior**

List that one, too.

**Additional context**

It was added to `standard/portability-issues.md` in <https://github.com/dotnet/csharpstandard/pull/759> but removed again in <https://github.com/dotnet/csharpstandard/commit/3a94e2b0cb037f9bc6df3c77f67bce81180f54d4>, which was then merged via <https://github.com/dotnet/csharpstandard/pull/238> and <https://github.com/dotnet/csharpstandard/pull/795>.

All other post-6.0 implementation-defined behaviors seem to be listed.  I did not search for post-6.0 undefined or unspecified behaviors.

**Comment by BillWagner** [comment]
Fixed in #863
