### ISSUE TITLE
§15.15.1 awaitable etc. requirements on nonstandard task types

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#868]
**Describe the bug**

In the C# 7.x draft, §15.15.1 (Async Functions / General), some of the specified aspects of task types should only apply to task types in the standard library.  (Currently Task, Task\<TResult>, ValueTask, and ValueTask\<TResult>).

**Example**

None.

**Expected behavior**

The C# standard should allow an application and an implementation to define a nonstandard task type that can be returned by an async function but does not match this paragraph:

> The exact definition of the task types is implementation-defined, but from the language’s point of view, a task type is in one of the states incomplete, succeeded or faulted. A faulted task records a pertinent exception. A succeeded «TaskType»\<T> records a result of type T. Task types are awaitable, and tasks can therefore be the operands of await expressions (§12.9.8).

Specifically:

* An implementation should not be required to document the exact definition of any nonstandard task types that it provides, any more than other nonstandard types.
* An implementation should not be required to document any task types that an application defines.
* A faulted task of a nonstandard task type should not be required to record an exception.
* A nonstandard task type should not be required to be awaitable.

**Additional context**

In some issue, awaitability was verified as not a requirement, but I don't have the link at hand.

**Comment by jskeet** [comment]
I think I disagree with at least some of this - I think it only makes sense to be able to have task types which are awaitable, and it's reasonable to at least document the *expected* behavior in terms of exceptions. I can't see much benefit in an implementation defining its own task types outside the "standard but non-attributed" (`Task` and `Task<T>`) and "non-standard but attributed". Is there a purpose you have in mind here?

I'll set this as a C# 7 milestone issue - we'll probably try to discuss it offline to avoid blocking a release.

**Comment by KalleOlaviNiemitalo** [comment]
I meant, if an implementation provides task types that are not specified by name in the standard, but that are decorated with AsyncMethodBuilderAttribute and have task builder types, then the standard should not require the implementation to document them just because they are task types, by stating that "exact definition of the task types is implementation-defined".

**Comment by jskeet** [comment]
Oh, I think I see what you mean. Would changing "implementation-defined" to "implementation-specific" be sufficient here?

**Comment by KalleOlaviNiemitalo** [comment]
Yes "implementation-specific" would be ok.  I see that term is already used in several places, although it is not defined in 3 Terms and definitions.  It is apparently different from "behavior, unspecified", for which the specification would provide "two or more possibilities".

**Comment by jskeet** [comment]
@RexJaeschke this is your area more than mine.  Thoughts?

**Comment by KalleOlaviNiemitalo** [comment]
although… if a nonstandard task type is defined in an application rather than in an implementation, then "implementation-specific" seems a bit wrong for that.  Instead could be "unspecified".

**Comment by jskeet** [comment]
Okay, I wonder whether we should make the change even broader - see the bold part below.

> **Task types can vary in their exact definition**, but from the language’s point of view, a task type is in one of the states incomplete, succeeded or faulted. A faulted task records a pertinent exception. A succeeded `«TaskType»<T>` records a result of type `T`. Task types are awaitable, and tasks can therefore be the operands of await expressions (§12.9.8).

**Comment by RexJaeschke** [comment]
Although "implementation-specific" is not a defined term, we use it to allow an implementation to do whatever it seems useful/appropriate without required it be documented. "unspecified" requires the spec to say what all the possibilities are.

**Comment by BillWagner** [comment]
Notes for 9/6 meeting:  

I like Jon's proposed change [here](https://github.com/dotnet/csharpstandard/issues/868#issuecomment-1669041471). When looking at this, I want to be careful that we don't restrict future compiler enhancements. The purpose of generalized async return types is for library or application authors to apply knowledge of a specific scenario to build a "better" task type, for some definition of "better". In terms of the code the compiler generates, it should be a replacement for `Task` and `Task<T>`. We should prefer language that constrains the author of a `TaskType` rather than the future compiler enhancements. I believe Jon's suggestion does that.

**Comment by KalleOlaviNiemitalo** [comment]
If the C# standard requires task types to be awaitable, but a user defines and uses a task type that is not awaitable and an implementation allows that, then it is an extension and will have to be documented by the vendor of the implementation.  So, this is one thing that would have to be added to the Roslyn extensions document.

Filed as <https://github.com/dotnet/roslyn/issues/69937>.
