### ISSUE TITLE
 C# 7.x §15.15.2 task builder "accessible" members

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#879]
**Describe the bug**

In the C# 7.x draft, §15.15.2 (Async functions / Task-type builder pattern) says that the task builder type must have "the following accessible members".  It is not clear what "accessible" means there.  Does it mean accessible by the async function, by the task type, or something else?  Can the members be `internal` if all relevant code is in the same assembly?

(In any case, the task type must be accessible by the async function, in order to be the return type; and the task builder type must be accessible by the task type, in order to be named in the AsyncMethodBuilderAttribute.)

**Example 1**

Is the following allowed?  The members are accessible by the async method and also by the task type.  Roslyn however rejects this code.  [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQCUCuAdgC4CWAtgKbYDCA9uQA6kA2lATgMocBupAxpQDOAbmTJY6GugDeydAswAOKfiHEGUAGzoAsgAoAlLIC+6APTn0HdnXZTOqLQFYtyE+KQBtAIJCAnoT8upTEABZ0wABC+KzAHPrE/oyUdABm+jRqGuTaMXEchoYAusikJByEAIYs6Ors+PzEquqabkhySB5IiuhlFezVtfWNzVmtuVr5LPH2nb3lxJU1mHA64zl5sTMcUuyUVUtG6AC8AHzo8WlV+CzEIhZWi8u1/DdCwujhlNbstuzyRRQADMmAALOhOMQquxiAAeAAqUMOlF0VX4YXKlDO+kBvQU+zS6CR0KWaIxWLqpNR6MxhEohjx+IA7mEOD8SSjyXSfiB0ABJPyBfjIsm0ykybq9EHgyGhUU0in03E9fEKQUBIIK7mU9Rc8X04ySpkyqAQ7jEACiAA9BIwyHRCCq1QobXaHYRrLbKPbSI6jVKgaCzXLiLhhLdiMdjaqFKaIT5mVVSMQAPKEehMNhLYCIxPJpbsAA0nLFSuxzpdhOJ+ZTuygAE4OEWmb1q6XFTyqfry4zYyy2fsa0m6/Y+fyAHJ0MhpfyZxjZv2EVuKVns4nag28gVCrXUnX00wm4MJkfEACqhCEVTSlHT8+zlFzCNrhZLm/LOJXBMoRJfZ/rJti2/dB2w/Ls9TLHk+xddA1yHf8C12ccpxnOcGAXUIlxA+COXAylx13EV9y3I9+xlDY2kwHRzkuX8bjuMQuiAA=)

```csharp
using System;
using System.Runtime.CompilerServices;

class C {
    async CustomTask M() {} // error CS0656
}

[AsyncMethodBuilder(typeof(CustomTaskBuilder))]
internal struct CustomTask
{
}
    
internal struct CustomTaskBuilder {
    internal static CustomTaskBuilder Create() => default; // internal causes the error
    public void Start<TStateMachine>(
        ref TStateMachine stateMachine)
        where TStateMachine : IAsyncStateMachine {}
    public void SetStateMachine(
        IAsyncStateMachine stateMachine) {}
    public void SetException(
        Exception exception) {}
    public void SetResult() {}
    public void AwaitOnCompleted<TAwaiter,TStateMachine>(
        ref TAwaiter awaiter,
        ref TStateMachine stateMachine)
        where TAwaiter : INotifyCompletion
        where TStateMachine : IAsyncStateMachine {}
    public void AwaitUnsafeOnCompleted<TAwaiter,TStateMachine>(
        ref TAwaiter awaiter,
        ref TStateMachine stateMachine)
        where TAwaiter : INotifyCompletion
        where TStateMachine : IAsyncStateMachine {}
    public CustomTask Task => default;
}
```

**Example 2**

Is the following allowed?  The task builder type is not accessible by the async method, so its members are not accessible by that either.  They are however accessible by the task type, and Roslyn allows this code.  [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQCUCuAdgC4CWAtgKbYDCA9uQA6kA2lATgMocBupAxpQDOAbmTJY6GugDeydAswAOdAHl8xDrXxDiDKADZ0AWQAUASlkBfdAHpbagNLIr4pKRIdCAQxaYYahocyHJIiugA2gCCQgCehPzGlMQAFnTAAEL4rMAcpsSxjJR0AGamxqTAwGzauvoGWTkc5uYAuvKKHprsPn667Pj8xFI6euSGHQqh4a5hipPojOykPN6a6P2DwxVVbAvT4Z2ePb4bxANDI3XjDdksueyyC4eKUADMmHBGNKP1jfccKTsShrSgWdAAXgAfOhciVvPgWMQxHMXuF3pgACzoTjEbzsYgAHgAKrjQcZvPwUh5KFDTM80eFgSV0KS8ZoKVSaWdyZTqYRKOYGYyFAB3FIcSisskcvnckDoACSMXi/BllE5/KlMlmIteHyg2O4xHVmpp9NResUyriCVNcoFPNlXIFlh1wsOGMNOOSAFEAB6CRhkOiEC1Ww4BoMhwjoSiByjB0iht26q1eo3JXDCRHEcHuy2MjPoKKi7ykYiqQj0JhsTTAEml8vdAA0bN5Ltp4YjimZrKbFcBUAAnBwWx7GX3286tU6NQ7BRO0eLJf2y4PHgrFQA5OhkEqxGuMOvJwhLl4r4HS9nzzvoLcqu03s2OgsR4sD4gAVUIQm8JUoKsjzrSgG2JT8x2nW8tTpc9DinCDHhHMc4KZSgWSgl8pV0DstSFQsrUvKVwPXbp7yVXd90PBhj2SU9UMUIjr1w+UlUfNVnwXaw4IxH5rkMTAjGhWF0IRJEUUZNMFFmKwgA==)

```csharp
using System;
using System.Runtime.CompilerServices;

class C {
    async Outer.CustomTask M() {} // OK
}

internal class Outer
{
    [AsyncMethodBuilder(typeof(Middle.CustomTaskBuilder))]
    internal struct CustomTask
    {
    }
    
    private struct Middle
    {
        internal struct CustomTaskBuilder {
            public static CustomTaskBuilder Create() => default;
            public void Start<TStateMachine>(
                ref TStateMachine stateMachine)
                where TStateMachine : IAsyncStateMachine {}
            public void SetStateMachine(
                IAsyncStateMachine stateMachine) {}
            public void SetException(
                Exception exception) {}
            public void SetResult() {}
            public void AwaitOnCompleted<TAwaiter,TStateMachine>(
                ref TAwaiter awaiter,
                ref TStateMachine stateMachine)
                where TAwaiter : INotifyCompletion
                where TStateMachine : IAsyncStateMachine {}
            public void AwaitUnsafeOnCompleted<TAwaiter,TStateMachine>(
                ref TAwaiter awaiter,
                ref TStateMachine stateMachine)
                where TAwaiter : INotifyCompletion
                where TStateMachine : IAsyncStateMachine {}
            public CustomTask Task => default;
        }
    }
}
```

**Example 3**

Is the following allowed?  As in Example 2, the task builder type is not accessible by the async method but is accessible by the task type. This time however, Roslyn rejects this code.  [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQCUCuAdgC4CWAtgKbYDCA9uQA6kA2lATgMocBupAxpQDOAbmTJY6GugDeydAswAOdAHl8xDrXxDiDKADZ0AWQAUASlkBfdAHpb6DuzrspnOAE4lAZmRXxSKQkHIQAhiyYMGoaHMhySIroANoAgkIAnoT8xpTEABZ0wABC+KzAHKbE6YyUdABmpjQ6euSGJWUc5uYAuvKKQZrsYRG67Pj8xFLN+gZ9CvGJ/gmKc+iM7KQ8oZroo+OTTboz7SzlrguJilDemHBGhy1tpaccUuyU25QW6AC8AHzocp1UL4FjEMTLS6YG5QAAs6E4xFC7GIAB4ACqIz7GUL8PJBSh/UyrKEKd51dCYpGaHF4gm7amUWn4wiUcwk0kAdzyHEolKxNNxLL5IHQAEk0pl+AKmUL6TIlqToZh4dxiDLmQTiZCleLJVkNXLWQzsUa2dYOQpriqEbkAKIAD0EjDIdEI2t1ikdztdhEcTsoLtIbssCstyrhtuIuGEoOI3zDOsS1sjKU5oVIxFUhHoTDYmmAGLTGcGABoqaa6ayieHEuTKcXM68oB4OKXa4p6xXBVW+bpK8L2UmuTz3g3003XKKxQA5OhkOrpXOMfPBwgdhTc3n8xma43T/XS3dmi3Dq0w+GN4gAVUIQlCdUo2eX+cohfRV7b3dlvZrZ8uXafq4LZthu6BdoavYmj2g5gVuY4fhOgzoNOc4LkuDArrka5waOfLfnuIp6hkBrHlBiZKtaDwzJgRj/IClDAnGEKLH4QA)

```csharp
using System;
using System.Runtime.CompilerServices;

class C {
    async Outer.CustomTask M() {} // error CS1983
}

internal class Outer
{
    [AsyncMethodBuilder(typeof(CustomTaskBuilder))]
    internal struct CustomTask
    {
    }
    
    private struct CustomTaskBuilder {
        public static CustomTaskBuilder Create() => default;
        public void Start<TStateMachine>(
            ref TStateMachine stateMachine)
            where TStateMachine : IAsyncStateMachine {}
        public void SetStateMachine(
            IAsyncStateMachine stateMachine) {}
        public void SetException(
            Exception exception) {}
        public void SetResult() {}
        public void AwaitOnCompleted<TAwaiter,TStateMachine>(
            ref TAwaiter awaiter,
            ref TStateMachine stateMachine)
            where TAwaiter : INotifyCompletion
            where TStateMachine : IAsyncStateMachine {}
        public void AwaitUnsafeOnCompleted<TAwaiter,TStateMachine>(
            ref TAwaiter awaiter,
            ref TStateMachine stateMachine)
            where TAwaiter : INotifyCompletion
            where TStateMachine : IAsyncStateMachine {}
        public CustomTask Task => default;
    }
}
```

**Example 4**

The same as Example 3, except now with `internal struct CustomTaskBuilder`.  The members are accessible by the async method and also by the task type.  Roslyn allows the code.  [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQCUCuAdgC4CWAtgKbYDCA9uQA6kA2lATgMocBupAxpQDOAbmTJY6GugDeydAswAOdAHl8xDrXxDiDKADZ0AWQAUASlkBfdAHpbagNLIr4pKRIdCAQxaYYahocyHJIiugA2gCCQgCehPzGlMQAFnTAAEL4rMAcpsSxjJR0AGamNDp65IZZORzm5gC68ooemuw+frrs+PzEUpX6Bi0KoeGuYYoj6G1evujdvf0VukO1LLnsstPhUADMmHBGK1U12RscUuyU3poW6AC8AHzouSXe+CzEYpPhCvuYAAs6E4xG87GIAB4ACqg26UYzefgpDyUJ6mHZ/BTXEroWFgzSI5GohYEhFIlGESjmTFYgDuKQ4lDxcMJFJJIHQAEkYvF+KzycSqdZaZgDlBgdxiAKiZTKBjfljFDy4gkZezhbp4bLUZYZBMlWKgSDkgBRAAegkYZDohAVhvCFqtNsI6Eolso1tItr1BqVAIlJuIuGEn2I931ooDwKidO8pGIqkI9CYbE0wBhsfj7QANPjtRq0faHdjKLjoVmE5coABODg50XhHEssk6zWtws0xWGhlMvGV9roTlcgBydDIJViKcYae9hEbil71xbBaFzOHvLVHbXIu7imj6AHAFVCEJvCVKEnp2nKBmK3Gq+w8+q1+iF6XywPq3Wn+/0M38zZHctSAuUuxLBQl2Ze9s0uYcxwnKcGBnZI5z/KCV1AjluU3fltzlXdDQBE4hkwIxnleMsPi+H5xhcIA)

**Example 5**

The same as Example 3, except now with `internal protected struct CustomTaskBuilder`.  The members are accessible by the async method and also by the task type.  Roslyn rejects the code, even though `internal protected` generally is *more* accessible than `internal`.  [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQCUCuAdgC4CWAtgKbYDCA9uQA6kA2lATgMocBupAxpQDOAbmTJY6GugDeydAswAOdAHl8xDrXxDiDKADZ0AWQAUASlkBfdAHpb6DuzrspnOAE4lAZmRXxSKQkHIQAhiyYMGoaHMhySIroANoAgkIAnoT8xpTEABZ0wABC+KzAHKbE6YyUdABmpjQ6euSGJWUc5uYAuvKKQZrsYRG67Pj8xFLN+gZ9CvGJ/gmKc+gDIeHojM6aE5TA6KPjk026M+0s5a4LiYpQ3phwRqctbaWXHFLslKGaFugAXgAfOhynVQvgWMQxMtbpgHlAACzoTjEULsYgAHgAKqjfpRjKF+HkgpQgaZVnCFN86uhcWjNITiaTDgyCUSSYRKOZKVSAO55DiUOl4xkclkgdAASTSmX4ovZzK51l5CnumGR3GICqZnMoFNhVIUMoyWR14uVunxutJlhkSyN6qRKNyAFEAB6CRhkOiEA1GxIer0+wiOT2Ub2kX12h1Up2a3K4YSQ4j/e2q+Ea9ApPmhUjEVSEehMNiaYA4nN5wYAGnp1otZP9AeplFp2Mr+c+UA8HGrGcSNJFbJtluHDZ5hqNAqFdI7g3QkqlADk6GQ6uli4xS1HCP3FNPvkP60rhYvZWaxyeVZO7gjkXOAKqEIShOqUQub0v7Cu5zvsWvmie5J7i2bZzl2Pb/iB6CDnWYpXla8F6hOzYKAewrtr+86Liua4bgwW65Du0HoUeSEStK57ypeerXo6DwvDMmBGMCoKthCUIwosfhAA==)

**Expected behavior**

Declare that the task builder type shall be accessible by the async function (and thus also by the generated state machine).
Declare that the listed members of the task builder type shall be `public`.  Do not say whether they are "accessible".

| Example | Roslyn (.NET SDK 7.0.109) | Expected behavior |
| --- | --- | --- |
| Example 1 | Reject | Reject, because member is not public |
| Example 2 | Allow | Reject, because task builder type is not accessible by async function |
| Example 3 | Reject | Reject, because task builder type is not accessible by async function |
| Example 4 | Allow | Allow |
| Example 5 | Reject | Allow |

**Additional context**

None.

---
[Associated WorkItem - 187391](https://dev.azure.com/msft-skilling/Content/_workitems/edit/187391)

**Comment by KalleOlaviNiemitalo** [comment]
**Alternative fix**

Declare that the task builder members shall be public.
Declare that the task type and task builder type shall have the same declared accessibility.
Declare that both types shall be declared in namespace scope or in the same containing type (which then cannot be a generic type).
Treat anything more complex as an extension.

| Example | Roslyn (.NET SDK 7.0.109) | Alternative fix |
| --- | --- | --- |
| Example 1 | Reject | Reject, because member is not public |
| Example 2 | Allow | Reject, because task builder type is nested but task type is not |
| Example 3 | Reject | Reject, because declared accessibility does not match |
| Example 4 | Allow | Allow |
| Example 5 | Reject | Reject, because declared accessibility does not match |

**Comment by jskeet** [comment]
Apologies, triaged this too late for C# 7. Will address address in C# 8.
