### ISSUE TITLE
TC49-TG2 dead link to HTML version of C# standard

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#881]
**Describe the bug**

At <https://www.ecma-international.org/task-groups/tc49-tg2/?tab=activities>, there is a dead link to an HTML version of C#.

**Example**

```HTML
<p>Jon Jagger has made an <a href="http://www.jaggersoft.com/csharp_standard/index.html">html</a> version of C#.</p>
```

**Expected behavior**

Delete the <http://www.jaggersoft.com/csharp_standard/index.html> link.  Perhaps link to this GitHub repository instead.

**Additional context**

The link redirects to <http://jonjagger.blogspot.com/>.  That blog has five posts tagged `c#`, but I don't see the C# standard there.

**Comment by jskeet** [comment]
Thanks Kalle. I'll see if I can get this fixed next week.

**Comment by Nigel-Ecma** [comment]
Its in the archive:

	https://web.archive.org/web/20160829045241/http://www.jaggersoft.com/csharp_standard/index.html <https://web.archive.org/web/20160829045241/http://www.jaggersoft.com/csharp_standard/index.html>

**Comment by KalleOlaviNiemitalo** [comment]
If you make the TG2 page link to the archive, please make it also say which version of C# that is.

**Comment by jskeet** [comment]
I've emailed ECMA about this, but the relevant person is out for a couple of weeks. I'll update this issue when I hear back.

**Comment by jskeet** [comment]
This has now been fixed :)
