### ISSUE TITLE
README.md references ECMA-354

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#882]
**Describe the bug**

In README.md, there is a reference to ECMA-354, which should instead be ECMA-334.

**Example**

<https://github.com/dotnet/csharpstandard/blob/f88ecc4612b278ef69813bd35331397cd669b041/README.md?plain=1#L46>

**Expected behavior**

Reference ECMA-334.

**Additional context**

[ECMA-334](https://www.ecma-international.org/publications-and-standards/standards/ecma-334/) is "C# language specification".

[ECMA-354](https://www.ecma-international.org/publications-and-standards/standards/ecma-354/) is "Application session services".

**Comment by KalleOlaviNiemitalo** [comment]
It's on the `standard-v5` branch too.

**Comment by jskeet** [comment]
> It's on the standard-v5 branch too.

Indeed, but I'm not sure whether we'll backport everything. Let's see what @BillWagner thinks.
