### ISSUE TITLE
§8.8: unmanaged type with static fields

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#891]
**Describe the bug**

C# 7.x draft §8.8 (Unmanaged types) appears to forbid an unmanaged type from having static fields with a managed type.

> An *unmanaged_type* is any type that isn’t a *reference_type*, a *type_parameter*, or a constructed type, and contains no fields whose type is not an *unmanaged_type*.

"contains no fields" might be understood as meaning both instance fields and static fields.

**Example**

Is this an unmanaged type?

```csharp
struct S {
    int i;
    static object obj;
}
```

**Expected behavior**

Static fields should not affect whether the type is an unmanaged type.

**Additional context**

Found while perusing <https://github.com/dotnet/csharpstandard/pull/888>.

**Comment by jskeet** [comment]
Yes, this sounds like an easy fix just to change it to "contains no instance fields".

@BillWagner does that match your expectations? If so, I'll create a tiny PR.

**Comment by KalleOlaviNiemitalo** [comment]
Thinking about other types not explicitly mentioned in the prose of §8.8:

- `void`: is not a type; it is just a keyword.
- tuple types: are constructed types.
- array types: are reference types.
- pointer types: are unmanaged types according to §23.3 (Pointer types).

So the current wording of §8.8 is OK for each of those.

**Comment by BillWagner** [comment]
@jskeet 

> Yes, this sounds like an easy fix just to change it to "contains no instance fields".

I agree. That reads as the correct fix.
