### ISSUE TITLE
Readonly structs in standard library

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#893]
**Describe the bug**

Of the struct types listed in Annex C of the C# 7.x draft, only a few are specified as `readonly struct`.  In .NET however, most of them are defined as `readonly struct`.
Is this allowed, and is it an extension?

**Example**

Types that are `readonly struct` in .NET but plain `struct` in Annex C include:

- System.Int32
- System.Span\<T>
- System.Runtime.CompilerServices.TaskAwaiter\<TResult>

**Expected behavior**

Could be solved in any of these ways:

- make them `readonly struct` in the standard, too
- declare that an implementation can add `readonly` to standard library struct types
- as above, but also change every `readonly struct` in Annex C to plain `struct`

**Additional context**

Similar to <https://github.com/dotnet/csharpstandard/issues/870> on attributes.

**Comment by KalleOlaviNiemitalo** [comment]
See also <https://github.com/dotnet/csharpstandard/issues/894> for an effect of `readonly struct` outside the struct type itself.

**Comment by jskeet** [comment]
Hmm... I'm tempted to go with the first option, although we'll probably need an explanatory note to explain why they're not the same as in ECMA 335.

@BillWagner, preferences for this? (I'm happy to create the PR.)

**Comment by BillWagner** [comment]
I like the first option with the Note: as well.

**Comment by jskeet** [comment]
Right - I'll try to prep a PR soon.
