### ISSUE TITLE
Clarity for reuse of local function name

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/csharpstandard#913]
**Describe the bug**

In section 7.3 (Declarations) of the C# 7.x draft, there is wording that disallows some reuse of names in local variable declaration spaces:

> - Additional local variable declaration spaces may occur within member declarations, anonymous functions and local functions. Names are introduced into these declaration spaces through *declaration_expression*s and *declaration_statement*s. Local variable declaration spaces may be nested, but it is an error for a local variable declaration space and a nested local variable declaration space to contain elements with the same name. Thus, within a nested declaration space it is not possible to declare a local variable or constant with the same name as a parameter, type parameter, local variable or constant in an enclosing declaration space. It is possible for two declaration spaces to contain elements with the same name as long as neither declaration space contains the other. Local declaration spaces are created by the following constructs:

In the paragraph quoted above, the "it is not possible to declare" sentence lists various kinds of declarations but not local functions.  However, the *declaration_statement* grammar rule includes *local_function_declaration*, and I think that means the name of a local function is introduced into a local variable declaration space and then cannot be reused.  §13.6.1 (Declaration statements / General):

> ```ANTLR
> declaration_statement
>     : local_variable_declaration ';'
>     | local_constant_declaration ';'
>     | local_function_declaration
>     ;
> ```

**Example**

Make it clearer that this is not allowed:

```csharp
class ShadowDemo {
    void Method() {
        void SameName() { }

        {
            void SameName() { }
        }
    }
}
```

**Expected behavior**

Explicitly list local functions in the "it is not possible to declare" sentence quoted above.

In addition, local functions and their parameters and type parameters could be mentioned in the following sentences, or perhaps it would be better to replace the sentences with notes that reference the constraints on "local variable declaration space" in §7.3:

* §13.6.2 (Local variable declarations):

  > Within the scope of a local variable, it is a compile-time error to declare another local variable or constant with the same name.

* §13.6.3 (Local constant declarations):

  > Within the scope of a local constant, it is a compile-time error to declare another local variable or constant with the same name.

**Additional context**

Other similar constraints:

* §13.6.4 (Local function declarations) says "unique in its declared block scope", which might not include enclosing scopes:

  > The identifier of a *local_function_declaration* must be unique in its declared block scope.

* §13.6.4 (Local function declarations) does not mention type parameters of local functions here, and "the enclosing scope" seems too tight as multiple enclosing scopes should be considered:

  > It is a compile-time error for a local function to declare a parameter or local variable with the same name as one declared in the enclosing scope.

* §15.6.2.1 (Method parameters / General):

  > It is an error for the method declaration space and the local variable declaration space of a nested declaration space to contain elements with the same name.

**Comment by jskeet** [comment]
Meeting 2023-09-06: I'll create a PR with the suggested changes and review it carefully. (Not prejudging whether there may be issues...)

**Comment by KalleOlaviNiemitalo** [comment]
"The identifier of a local_function_declaration must be unique in its declared block scope" in §13.6.4 (Local function declarations)  might be understood as disallowing the following:

```csharp
public class C {
    public void M() {
        NotUnique:
        void NotUnique() {}
    }
}
```

as the label is in the block scope according to §7.7.1 (Scopes / General):

> The scope of a label declared in a *labeled_statement* (§13.5) is the block in which the declaration occurs.

This could perhaps be fixed by making the constraint "The identifier of a local_function_declaration must be unique in its declared block scope" reference declaration spaces rather than scopes.  The label is in a "label declaration space" according to §7.3 (Declarations) and the local function is not.

§7.7.1 (Scopes / General) doesn't seem to specify that the name of a local function is in any scope.  §13.6.4 (Local function declarations) does not specify that either; it says "A local function is declared at block scope" but does not say that this scope is the scope of the name of the local function.
