### ISSUE TITLE
Redundant statement regarding ref local initialization?

### ISSUE THREAD

**Issue by Nigel-Ecma** [dotnet/csharpstandard#923]
In #910 @KalleOlaviNiemitalo asks whether in §13.6.2 when covering the intialization of a ref local whether the statement:

> It is a compile time error if the scope of the local variable is wider than the ref-safe-context of the *variable_reference* (§9.7.2).

is redundant as it seems impossible to have this situation (it is not impossible in *ref assignment*).

As the statement is at worst harmless (forbidding the impossible) resolution can be left till after v7.x and this issue is being left as a marker.

---
[Associated WorkItem - 178986](https://dev.azure.com/msft-skilling/Content/_workitems/edit/178986)

**Comment by BillWagner** [comment]
Adding the meeting discuss label. The text referenced in this issue has already been removed.

@Nigel-Ecma removed the sentence in #940 

cc @jskeet to add to the agenda.

**Comment by jskeet** [comment]
Validated that the text has already been removed. Closing.
