### ISSUE TITLE
Verify pattern description with interactions with discards and tuples

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#936]
See https://github.com/dotnet/csharpstandard/pull/757#discussion_r1326602356

In 17.2.2 we have:

> Given a *pattern input value* *e*, if the *simple_designation* is the *identifier* `_`, it denotes a discard (§discards-new-clause) the value of *e* is not bound to anything. (Although a declared variable with the name `_` may be in scope at that point, that named variable is not seen in this context.) If *simple_designation* is any other identifier, a local variable (§9.2.8) of the given type named by the given identifier is introduced. That local variable is assigned the value of the *pattern input value* when the pattern *matches* the value.

This may need modification (or even just links) now that the work for tuples and discards has been merged.

Deferred to post C# 7.

---
[Associated WorkItem - 187390](https://dev.azure.com/msft-skilling/Content/_workitems/edit/187390)

**Comment by BillWagner** [comment]
The new section in patterns already references the definition of discards. I don't believe any action is needed to address this one.

Proposal: Close without further action.

Adding the meeting discuss and proposal labels.

**Comment by jskeet** [comment]
We can't see anything that needs doing here. Closing without action - we can always revisit if we find something.
