### ISSUE TITLE
Complete V7 admin status

### ISSUE THREAD

**Issue by BillWagner** [dotnet/csharpstandard#951]
The [admin status file](https://github.com/dotnet/csharpstandard/blob/standard-v7/admin/v7-feature-tracker.md) for V7 doesn't reflect the fact that we've finished V7. 

We should update that. Ideally on the V7 standard branch, so that it matches the actual standard.

**Comment by KalleOlaviNiemitalo** [comment]
Also README.md here as the branch is no longer called `draft-v7`. 

<https://github.com/dotnet/csharpstandard/blob/47912d4fdae2bb8c3750e6485bdc6509560ec6bf/README.md?plain=1#L12-L14>

**Comment by KalleOlaviNiemitalo** [comment]
The table at <https://www.ecma-international.org/task-groups/tc49-tg2/> currently shows "V7.0" under "Microsoft Visual C# Version".  Will that be changed to "V7.3"?  The "standard.docx" from <https://github.com/dotnet/csharpstandard/pull/949#issuecomment-1729325243> just says "C# Language Specification Version 7" without minor versions.

**Comment by BillWagner** [comment]
Fixed in #955

**Comment by BillWagner** [comment]
> The table at https://www.ecma-international.org/task-groups/tc49-tg2/ currently shows "V7.0" under "Microsoft Visual C# Version". Will that be changed to "V7.3"? The "standard.docx" from [#949 (comment)](https://github.com/dotnet/csharpstandard/pull/949#issuecomment-1729325243) just says "C# Language Specification Version 7" without minor versions.

We'll need to take this up at the committee.  Pinging @jskeet to make sure it's on our agenda next meeting.
