### ISSUE TITLE
Need help spec'ing V8 feature, "Permit stackalloc in nested contexts"

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#967]
Nearly 4 years ago, @gafter uploaded the MS spec for this feature ([MS Spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/nested-stackalloc.md#permit-stackalloc-in-nested-contexts)).

I'm having difficulty reconciling that spec with [12.8.21](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#12821-stack-allocation) that we now have in draft-V8. (See also in unsafe code: [23.9](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/unsafe-code.md#239-stack-allocation).) 

In draft-v8 we say:
> \
> A *stackalloc_expression* is only permitted in two contexts:
> ...
>In both contexts the *stackalloc_expression* is only permitted to occur as:
> ...
> \

My tests show that V8 allows the following:

```csharp
M(stackalloc[] { 1, 2, 3, 4, 5, 6 });
M(val ? stackalloc[] { 1, 2} : stackalloc[] { 4, 5, 6 });
```

Where `M` is declared as `public static void M(Span<int> sp) { }`.

So that is at least one (and maybe 2) new context. Are there others? What about the MS proposal's mention of a new implicit conversion?

**Comment by jskeet** [comment]
Bill will reach out internally.

**Comment by BillWagner** [comment]
I think I can answer this one.  Adding @jaredpar @MadsTorgersen to verify or make corrections.

Relaxing the earlier restrictions is a benefit of being able to assign a `stackalloc`ed expression to a `Span<T>` instance. `Span` is a `ref struct` must obey all ref safety rules, it can be safely initialized to storage allocated with `stackalloc`: The ref safety rules ensure that the `Span` can't be copied out of its safe context.

Which contexts are allowed? Well, any context where a *primary_no_array_creation_expression* is allowed. The updated grammar for a *stackalloc_initializer* indicates that a `stackalloc` expression may be part of a containing expression (like initializing a `ref struct` that contains two or more `Span` types.

I think you can remove all of this text for C# 8:

```
<!-- The following restrictions apply to C# 7.3, they are relaxed in C# 8 -->
A *stackalloc_expression* is only permitted in two contexts:

1. The initializing *expression*, `E`, of a *local_variable_declaration* ([§13.6.2](statements.md#1362-local-variable-declarations)); and
2. The right operand *expression*, `E`, of a simple assignment ([§12.21.2](expressions.md#12212-simple-assignment)) which itself occurs as a *expression_statement* ([§13.7](statements.md#137-expression-statements))

In both contexts the *stackalloc_expression* is only permitted to occur as:

- The whole of `E`; or
- The second and/or third operands of a *conditional_expression* ([§12.18](expressions.md#1218-conditional-operator)) which is itself the whole of `E`.
<!-- End of C# 7.3 restrictions -->
```

**Comment by gafter** [comment]
The purpose of the restriction in 7.3 was to ensure that the stackalloc instruction could be emitted when the runtime evaluation stack is empty, because that's a restriction of the underlying stackalloc instruction. It turns out that there might have been some situations - like passing it as a parameter to a static method - that might have satisfied the runtime restriction and was permitted (against the specification) anyway.

What changed in 8 was that I created a mechanism for the C# code generator to generate the stackalloc instruction when the stack is empty no matter what the context is, essentially by spilling the evaluation stack and then unspilling it again.

**Comment by RexJaeschke** [comment]
Thanks, @BillWagner. That's exactly the change I'll make, plus I'll add the new implicit conversion from T* to Span<T> in unsafe mode uses.

That answers all outstanding questions.

**Comment by RexJaeschke** [comment]
Closing this.
