### ISSUE TITLE
12.2.1 "Final result"

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#97]
After the bulleted list, we have:

> The final result of an expression is never a namespace, type, method group or event access. Rather, as noted above, these categories of expressions are intermediate constructs that are only permitted in certain contexts.

It's not clear what "final result" means here. Could we clarify? (I'm not proposing anything, as I'm unsure of the intention.)

**Comment by jskeet** [comment]
Reassigned Rex, but no work is currently required as #231 is out for review.

**Comment by RexJaeschke** [comment]
PR #231 addresses this.
