### ISSUE TITLE
Proposal to change all occurrences of “implementation-specific” to “implementation-defined”

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/csharpstandard#974]
The spec contains the following term definition:
 
> - behavior, implementation-defined – unspecified behavior where each implementation documents how the choice is made

and we pull together all uses of this term in [B.3 Implementation-defined behavior](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/portability-issues.md#b3-implementation-defined-behavior).
 
*Separately,* in 11 places, we use the term “implementation-specific,” presumably to allow difference in implementation but *without* requiring the implementer to document this. We do *not* define this term, and we do *not* gather together such uses in the Portability Annex B, although such uses clearly impact portability. (Note that V1 had only one use of this term, in the discussion of “Application domain.”)

In private conversations with Mads and Bill, they indicated they would be OK with this proposal, since it is very likely that implementations will need to document this information anyway for their own customers. This would also result in these cases being added to Annex B.3.

For completeness, here are the existing occurrences in V7:

1. [6.1 Lexical structure|Programs](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/lexical-structure.md#61-programs): *Note*: The handling of the Unicode NULL character (U+0000) is implementation-specific. It is strongly recommended that developers avoid using this character in their source code, for the sake of both portability and readability. When the character is required within a character or string literal, the escape sequences `\0` or `\u0000` may be used instead. *end note*
1. [7 Basic concepts|Application startup](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md#71-application-startup): A program may be compiled either as a ***class library*** to be used as part of other applications, or as an ***application*** that may be started directly. The mechanism for determining this mode of compilation is implementation-specific and external to this specification.
1. [7 Basic concepts|Application startup](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md#71-application-startup): An application domain enables application isolation by acting as a container for application state. An application domain acts as a container and boundary for the types defined in the application and the class libraries it uses. Types loaded into one application domain are distinct from the same types loaded into another application domain, and instances of objects are not directly shared between application domains. For instance, each application domain has its own copy of static variables for these types, and a static constructor for a type is run at most once per application domain. Implementations are free to provide implementation-specific policy or mechanisms for the creation and destruction of application domains.
1. [7.2 Basic concepts|Application termination](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md#72-application-termination): If the effective entry point method terminates due to an exception ([§21.4](exceptions.md#214-how-exceptions-are-handled)), the exit code is implementation-specific. Additionally, the implementation may provide alternative APIs for specifying the exit code.
1. [7.2 Basic concepts|Application termination](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md#72-application-termination): Whether or not finalizers ([§15.13](classes.md#1513-finalizers)) are run as part of application termination is implementation-specific.
1. [7.9 Basic concepts|Automatic memory management](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md#79-automatic-memory-management): Once the object is eligible for finalization, at some unspecified later time the finalizer ([§15.13](classes.md#1513-finalizers)) (if any) for the object is run. Under normal circumstances the finalizer for the object is run once only, though implementation-specific APIs may allow this behavior to be overridden.
1. [7.9 Basic concepts|Automatic memory management](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md#79-automatic-memory-management): Like other languages that assume the existence of a garbage collector, C# is designed so that the garbage collector might implement a wide range of memory management policies. C# specifies neither a time constraint within that span, nor an order in which finalizers are run. Whether or not finalizers are run as part of application termination is implementation-specific ([§7.2](basic-concepts.md#72-application-termination)).
1. [8.6 Types|Expression tree types](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/types.md#86-expression-tree-types): The API surface provided by `Expression<TDelegate>` is implementation-specific beyond the requirement for a `Compile` method described above.
1. [8.6 Types|Expression tree types](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/types.md#86-expression-tree-types): *Note*: While the details of the API provided for expression trees are implementation-specific, it is expected that an implementation will: 1) Enable code to inspect and respond to the structure of an expression tree created as the result of a conversion from a lambda expression, 2) Enable expression trees to be created programatically within user code *end note*
1. [10.7.3 Conversions|Evaluation of lambda expression conversions to expression tree types](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/conversions.md#1073-evaluation-of-lambda-expression-conversions-to-expression-tree-types): Not every lambda expression can be converted to expression tree types. The conversion to a compatible delegate type always *exists*, but it may fail at compile-time for implementation-specific reasons.
1. [22.5.1, Attributes|General](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/attributes.md#2251-general): An execution environment may provide additional implementation-specific attributes that affect the execution of a C# program.

**Comment by jskeet** [comment]
Agreed in meeting 2024-09-04.
